#include "luma/client/ui/scene_editor/SceneEditorView.hpp"
#ifdef _WIN32
#include <windowsx.h>
#include <algorithm>
namespace luma::client::ui::scene_editor {
using namespace client::domain::studio;
bool SceneEditorView::Create(HINSTANCE instance,int showCommand){
 const wchar_t cls[]=L"LumaLiveSceneEditor"; WNDCLASSW wc{}; wc.hInstance=instance; wc.lpfnWndProc=&SceneEditorView::WndProc; wc.lpszClassName=cls; wc.hCursor=LoadCursorW(nullptr,IDC_ARROW); if(!RegisterClassW(&wc)&&GetLastError()!=ERROR_CLASS_ALREADY_EXISTS)return false;
 hwnd_=CreateWindowExW(0,cls,L"LumaLive Studio - Scene Editor",WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN,CW_USEDEFAULT,CW_USEDEFAULT,1280,760,nullptr,nullptr,instance,this); if(!hwnd_)return false; ShowWindow(hwnd_,showCommand);UpdateWindow(hwnd_);return true;
}
LRESULT CALLBACK SceneEditorView::WndProc(HWND w,UINT m,WPARAM wp,LPARAM lp){SceneEditorView* self=reinterpret_cast<SceneEditorView*>(GetWindowLongPtrW(w,GWLP_USERDATA));if(m==WM_NCCREATE){auto* cs=reinterpret_cast<CREATESTRUCTW*>(lp);self=static_cast<SceneEditorView*>(cs->lpCreateParams);SetWindowLongPtrW(w,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(self));self->hwnd_=w;}return self?self->Handle(m,wp,lp):DefWindowProcW(w,m,wp,lp);}
LRESULT SceneEditorView::Handle(UINT m,WPARAM wp,LPARAM lp){switch(m){case WM_PAINT:{PAINTSTRUCT ps{};HDC dc=BeginPaint(hwnd_,&ps);Paint(dc);EndPaint(hwnd_,&ps);return 0;}case WM_LBUTTONDOWN:{SetCapture(hwnd_);dragStart_.x=GET_X_LPARAM(lp);dragStart_.y=GET_Y_LPARAM(lp);HitTestAndSelect(dragStart_);dragging_=true;return 0;}case WM_MOUSEMOVE:if(dragging_&&(wp&MK_LBUTTON)&&!selected_.empty()){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};double dx=p.x-dragStart_.x,dy=p.y-dragStart_.y;if(app_.SceneEditor().MoveSelectedLayer(dx,dy)){dragStart_=p;InvalidateRect(hwnd_,nullptr,FALSE);}return 0;}break;case WM_LBUTTONUP:ReleaseCapture();dragging_=false;return 0;case WM_KEYDOWN:if(wp=='Z'&&(GetKeyState(VK_CONTROL)&0x8000)){app_.Undo();InvalidateRect(hwnd_,nullptr,FALSE);return 0;}if(wp=='Y'&&(GetKeyState(VK_CONTROL)&0x8000)){app_.Redo();InvalidateRect(hwnd_,nullptr,FALSE);return 0;}break;case WM_DESTROY:PostQuitMessage(0);return 0;}return DefWindowProcW(hwnd_,m,wp,lp);}
void SceneEditorView::HitTestAndSelect(POINT p){auto sid=app_.SceneGraph().GetActiveSceneId();if(!sid)return;auto scene=app_.SceneGraph().GetScene(*sid);if(!scene)return;std::sort(scene->layers.begin(),scene->layers.end(),[](const Layer&a,const Layer&b){return a.zOrder>b.zOrder;});for(const auto& l:scene->layers){if(!l.visible||l.locked)continue;if(p.x>=l.transform.x&&p.x<=l.transform.x+l.transform.width&&p.y>=l.transform.y&&p.y<=l.transform.y+l.transform.height){if(app_.SceneEditor().SelectLayer(l.id))selected_=l.id;InvalidateRect(hwnd_,nullptr,FALSE);return;}}app_.SceneEditor().ClearSelection();selected_.clear();InvalidateRect(hwnd_,nullptr,FALSE);}
void SceneEditorView::Paint(HDC dc){RECT rc{};GetClientRect(hwnd_,&rc);FillRect(dc,&rc,static_cast<HBRUSH>(GetStockObject(BLACK_BRUSH)));auto sid=app_.SceneGraph().GetActiveSceneId();if(!sid)return;auto scene=app_.SceneGraph().GetScene(*sid);if(!scene)return;for(const auto& l:scene->layers){if(!l.visible)continue;RECT r{static_cast<LONG>(l.transform.x),static_cast<LONG>(l.transform.y),static_cast<LONG>(l.transform.x+l.transform.width),static_cast<LONG>(l.transform.y+l.transform.height)};HBRUSH b=CreateSolidBrush(l.id==selected_?RGB(35,120,180):RGB(55,55,65));FillRect(dc,&r,b);DeleteObject(b);FrameRect(dc,&r,static_cast<HBRUSH>(GetStockObject(WHITE_BRUSH)));SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(235,235,235));DrawTextW(dc,std::wstring(l.name.begin(),l.name.end()).c_str(),-1,&r,DT_CENTER|DT_VCENTER|DT_SINGLELINE);}}
}
#endif
