# ============================================================
# Prepare-WebRTC.ps1
#
# LumaLive WebRTC environment preparation script
#
# Checks the local WebRTC source/header tree and GN Release
# output, then generates a CMake configuration file.
#
# This script does NOT download, copy, modify, or delete WebRTC.
# ============================================================

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "============================================================"
Write-Host " LumaLive WebRTC Environment Preparation"
Write-Host "============================================================"
Write-Host ""

$EnvironmentRoot = "D:\project\luma-live\LumaLive_Environment_Installer"
$WebRtcRoot      = Join-Path $EnvironmentRoot "third_party\src"
$WebRtcOut       = Join-Path $WebRtcRoot "out\Release"
$WebRtcObj       = Join-Path $WebRtcOut "obj"
$ToolsRoot       = Join-Path $EnvironmentRoot "tools"
$ConfigRoot      = Join-Path $EnvironmentRoot "cmake"
$WebRtcLib       = Join-Path $WebRtcObj "webrtc.lib"

function Test-RequiredPath {
    param(
        [string]$Path,
        [string]$Description
    )

    if (Test-Path $Path) {
        Write-Host "[OK]   $Description"
        Write-Host "       $Path"
        return $true
    }

    Write-Host "[FAIL] $Description"
    Write-Host "       $Path"
    return $false
}

$ok = $true
$ok = (Test-RequiredPath $WebRtcRoot "WebRTC source root") -and $ok
$ok = (Test-RequiredPath $WebRtcOut "WebRTC Release output") -and $ok
$ok = (Test-RequiredPath $WebRtcObj "WebRTC object/lib directory") -and $ok
$ok = (Test-RequiredPath $WebRtcLib "WebRTC umbrella library") -and $ok

Write-Host ""
Write-Host "------------------------------------------------------------"
Write-Host " Checking WebRTC headers"
Write-Host "------------------------------------------------------------"

$RequiredHeaders = @(
    "api\peer_connection_interface.h",
    "api\create_modular_peer_connection_factory.h",
    "api\environment\environment_factory.h",
    "api\enable_media_with_defaults.h",
    "api\media_stream_interface.h",
    "api\jsep.h",
    "rtc_base\thread.h",
    "rtc_base\ref_counted_object.h"
)

$HeaderFailures = 0

foreach ($relativePath in $RequiredHeaders) {
    $fullPath = Join-Path $WebRtcRoot $relativePath

    if (Test-Path $fullPath) {
        Write-Host "[OK]   $relativePath"
    }
    else {
        Write-Host "[FAIL] $relativePath"
        $HeaderFailures++
    }
}

if ($HeaderFailures -gt 0) {
    $ok = $false
}

Write-Host ""
Write-Host "------------------------------------------------------------"
Write-Host " Checking WebRTC libraries"
Write-Host "------------------------------------------------------------"

$RequiredLibs = @(
    "webrtc.lib",
    "api\create_modular_peer_connection_factory.lib",
    "api\create_peerconnection_factory.lib",
    "api\peer_connection_interface.lib",
    "api\rtc_error.lib",
    "api\transport_api.lib",
    "pc\peer_connection.lib",
    "pc\peer_connection_factory.lib",
    "pc\peer_connection_message_handler.lib",
    "pc\webrtc_session_description_factory.lib",
    "rtc_base\rtc_certificate_generator.lib",
    "rtc_base\rtc_event.lib",
    "rtc_base\rtc_numerics.lib",
    "rtc_base\rtc_operations_chain.lib",
    "rtc_base\rtc_task_queue_win.lib",
    "media\rtc_audio_video.lib",
    "modules\audio_coding\webrtc_opus.lib",
    "modules\rtp_rtcp\rtp_rtcp.lib"
)

$LibFailures = 0

foreach ($relativePath in $RequiredLibs) {
    $fullPath = Join-Path $WebRtcObj $relativePath

    if (Test-Path $fullPath) {
        Write-Host "[OK]   $relativePath"
    }
    else {
        Write-Host "[WARN] $relativePath"
        $LibFailures++
    }
}

Write-Host ""
Write-Host "------------------------------------------------------------"
Write-Host " WebRTC library statistics"
Write-Host "------------------------------------------------------------"

$AllLibs = @(Get-ChildItem -Path $WebRtcObj -Recurse -Filter "*.lib" -File -ErrorAction SilentlyContinue)

Write-Host "[INFO] Total .lib files found: $($AllLibs.Count)"

if ($AllLibs.Count -gt 0) {
    $TotalSize = ($AllLibs | Measure-Object -Property Length -Sum).Sum
    $TotalSizeMB = [math]::Round($TotalSize / 1MB, 2)
    Write-Host "[INFO] Total .lib size: $TotalSizeMB MB"
}

if (Test-Path $WebRtcLib) {
    $WebRtcLibInfo = Get-Item $WebRtcLib
    Write-Host "[INFO] webrtc.lib size: $([math]::Round($WebRtcLibInfo.Length / 1MB, 2)) MB"
}

New-Item -ItemType Directory -Force -Path $ToolsRoot | Out-Null
New-Item -ItemType Directory -Force -Path $ConfigRoot | Out-Null

$ConfigFile = Join-Path $ConfigRoot "LumaLiveWebRTC.cmake"

$ConfigContent = @"
# ============================================================
# LumaLiveWebRTC.cmake
#
# Generated by Prepare-WebRTC.ps1
# ============================================================

set(LUMALIVE_WEBRTC_ROOT
    "$($WebRtcRoot.Replace('\','/'))"
    CACHE PATH
    "LumaLive WebRTC source/header root"
)

set(LUMALIVE_WEBRTC_OUT
    "$($WebRtcOut.Replace('\','/'))"
    CACHE PATH
    "LumaLive WebRTC GN Release output directory"
)

set(LUMALIVE_WEBRTC_OBJ
    "$($WebRtcObj.Replace('\','/'))"
    CACHE PATH
    "LumaLive WebRTC object/lib directory"
)

set(LUMALIVE_WEBRTC_LIB
    "$($WebRtcLib.Replace('\','/'))"
    CACHE FILEPATH
    "LumaLive WebRTC umbrella library"
)

set(LUMALIVE_WEBRTC_GENERATED_BY_PREPARE_SCRIPT
    TRUE
    CACHE BOOL
    "Whether the WebRTC configuration was generated by Prepare-WebRTC.ps1"
)

message(STATUS "LumaLive WebRTC root: \${LUMALIVE_WEBRTC_ROOT}")
message(STATUS "LumaLive WebRTC output: \${LUMALIVE_WEBRTC_OUT}")
message(STATUS "LumaLive WebRTC lib: \${LUMALIVE_WEBRTC_LIB}")
"@

Set-Content -Path $ConfigFile -Value $ConfigContent -Encoding UTF8

Write-Host ""
Write-Host "[OK] Generated:"
Write-Host "     $ConfigFile"

$ReportFile = Join-Path $ToolsRoot "WebRTC-Environment-Report.txt"

$Report = @"
============================================================
LumaLive WebRTC Environment Report
============================================================

Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

Environment Root:
$EnvironmentRoot

WebRTC Root:
$WebRtcRoot

WebRTC Release:
$WebRtcOut

WebRTC Object/Lib:
$WebRtcObj

Umbrella Library:
$WebRtcLib

Header Failures:
$HeaderFailures

Library Warnings:
$LibFailures

Total LIB files:
$($AllLibs.Count)

============================================================
"@

Set-Content -Path $ReportFile -Value $Report -Encoding UTF8

Write-Host "[OK] Generated:"
Write-Host "     $ReportFile"

$env:LUMALIVE_WEBRTC_ROOT = $WebRtcRoot
$env:LUMALIVE_WEBRTC_OUT  = $WebRtcOut
$env:LUMALIVE_WEBRTC_OBJ  = $WebRtcObj

Write-Host ""
Write-Host "============================================================"

if ($ok) {
    Write-Host " WebRTC environment check: PASS"
    Write-Host "============================================================"
    Write-Host ""
    Write-Host "WebRTC headers and core build output are available."
    Write-Host ""
}
else {
    Write-Host " WebRTC environment check: FAILED"
    Write-Host "============================================================"
    Write-Host ""
    Write-Host "Please fix the missing WebRTC components before continuing."
    Write-Host ""
    exit 1
}
