add_library(luma_client_im STATIC src/ImClientService.cpp)
target_include_directories(luma_client_im PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_compile_features(luma_client_im PUBLIC cxx_std_20)
add_executable(luma_client_im_tests tests/ImClientServiceTests.cpp)
target_link_libraries(luma_client_im_tests PRIVATE luma_client_im)
add_test(NAME luma_client_im_tests COMMAND luma_client_im_tests)
