#include "StudioPreview.hpp"
#include "MeetingMedia.hpp"
#include "MeetingSpeaker.hpp"
#include "PreviewMedia.hpp"
#include "AudioOutput.hpp"
#include "DeviceCaptureFactory.hpp"
#include "ScreenCaptureService.hpp"
#include <commctrl.h>
#include <objbase.h>
#include <fstream>
#include <filesystem>
#include <dwmapi.h>
#include <array>
#include <thread>
#include <windowsx.h>
#include <chrono>
#include <algorithm>
namespace luma::client::ui::preview {
namespace {
std::wstring wide(const std::string& s){int n=MultiByteToWideChar(CP_UTF8,0,s.data(),int(s.size()),nullptr,0);std::wstring out(n,L' ');MultiByteToWideChar(CP_UTF8,0,s.data(),int(s.size()),out.data(),n);return out;}
std::string utf8(const std::wstring& s){int n=WideCharToMultiByte(CP_UTF8,0,s.data(),int(s.size()),nullptr,0,nullptr,nullptr);std::string out(n,' ');WideCharToMultiByte(CP_UTF8,0,s.data(),int(s.size()),out.data(),n,nullptr,nullptr);return out;}
class MeetingWindow {
 enum{Server=200,Room,Identity,Create,Join,Leave,Camera,Microphone,Screen,Speaker,Peers,Remove,End,CameraDevice,MicDevice,Refresh,Pin,Mode,Fullscreen,Copy,Count};
 HWND window_{};std::array<HWND,Count-Server> controls_{};HFONT font_{};HBRUSH background_=CreateSolidBrush(RGB(8,10,13));
 MeetingMedia meeting_;std::unique_ptr<media::IDeviceCaptureService> capture_;media::ScreenCaptureService screen_;AudioOutput output_;
 std::mutex frameMutex_;std::map<std::string,std::shared_ptr<VideoFrame>> frames_;std::string self_;std::wstring status_=L"设备默认关闭，准备好后再开启摄像头和麦克风";
 std::atomic<bool> running_{true},playing_{false},audioError_{false};std::thread audioThread_;bool closed_=false,muted_=false;std::vector<std::string> roster_;
 std::vector<media::CaptureDeviceInfo> cameras_,mics_;
 std::string pinned_,activeSpeaker_;bool focusMode_=false,speakerMode_=false,full_=false;
 std::map<std::string,std::pair<float,std::chrono::steady_clock::time_point>> levels_;
 MeetingSpeaker speakerSelection_;WINDOWPLACEMENT placement_{sizeof(WINDOWPLACEMENT)};LONG_PTR oldStyle_{};
 std::chrono::steady_clock::time_point connected_{};bool wasJoined_=false;HFONT titleFont_{};
 UINT dpi_=96;HFONT controlFont_{};
 int width_=1280,height_=850;
 int pixels(int value)const{return MulDiv(value,int(dpi_),96);}
 RECT logical(RECT r)const{return {MulDiv(r.left,96,int(dpi_)),MulDiv(r.top,96,int(dpi_)),MulDiv(r.right,96,int(dpi_)),MulDiv(r.bottom,96,int(dpi_))};}
 struct ScaleDC{HDC dc;int saved;ScaleDC(HDC h,UINT dpi):dc(h),saved(SaveDC(h)){SetMapMode(dc,MM_ANISOTROPIC);SetWindowExtEx(dc,96,96,nullptr);SetViewportExtEx(dc,int(dpi),int(dpi),nullptr);}~ScaleDC(){RestoreDC(dc,saved);}};
 void setDpi(UINT dpi){dpi_=std::max(96u,dpi);auto next=CreateFontW(-pixels(16),0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,0,0,0,0,L"Microsoft YaHei UI");if(next){for(auto h:controls_)if(h)SendMessageW(h,WM_SETFONT,reinterpret_cast<WPARAM>(next),TRUE);if(controlFont_)DeleteObject(controlFont_);controlFont_=next;}if(control(Peers))SendMessageW(control(Peers),LB_SETITEMHEIGHT,0,pixels(58));for(int id:{CameraDevice,MicDevice})if(control(id)){SendMessageW(control(id),CB_SETITEMHEIGHT,0,pixels(30));SendMessageW(control(id),CB_SETITEMHEIGHT,WPARAM(-1),pixels(30));}layout();InvalidateRect(window_,nullptr,TRUE);}

 std::string selected(){auto i=SendMessageW(control(Peers),LB_GETCURSEL,0,0);return i>=0&&size_t(i)<roster_.size()?roster_[i]:std::string{};}
 void refreshDevices(){
  auto fill=[&](int id,std::vector<media::CaptureDeviceInfo>& items,media::CaptureDeviceType kind){auto old=SendMessageW(control(id),CB_GETCURSEL,0,0);std::string previous=old>=0&&size_t(old)<items.size()?items[old].id:"";items=capture_->EnumerateDevices(kind).devices;SendMessageW(control(id),CB_RESETCONTENT,0,0);int chosen=0;for(size_t i=0;i<items.size();++i){auto name=wide(items[i].name);SendMessageW(control(id),CB_ADDSTRING,0,reinterpret_cast<LPARAM>(name.c_str()));if(items[i].id==previous)chosen=int(i);}if(items.empty())SendMessageW(control(id),CB_ADDSTRING,0,reinterpret_cast<LPARAM>(L"未找到设备"));SendMessageW(control(id),CB_SETCURSEL,chosen,0);};
  fill(CameraDevice,cameras_,media::CaptureDeviceType::Camera);fill(MicDevice,mics_,media::CaptureDeviceType::Microphone);
 }
 void level(const std::string& id,const AudioFrame& audio){const auto peak=Peak(audio);std::lock_guard lock(frameMutex_);levels_[id]={peak,std::chrono::steady_clock::now()};}
 void updateSpeaker(){
  const auto now=std::chrono::steady_clock::now();std::set<std::string> eligible;std::map<std::string,float> fresh;
  for(const auto& [id,member]:meeting_.Session().Members())if(member.microphone)eligible.insert(id);
  {std::lock_guard lock(frameMutex_);for(auto it=levels_.begin();it!=levels_.end();){
   if(!eligible.count(it->first)||now-it->second.second>=std::chrono::milliseconds(350)){it=levels_.erase(it);continue;}
   fresh[it->first]=it->second.first;++it;
  }}
  activeSpeaker_=speakerSelection_.Update(eligible,fresh,now);
 }
 bool confirmLeave(){return !meeting_.Session().IsHost()||MessageBoxW(window_,L"你是主持人。离开将结束所有成员的会议，确定离开？",L"离开会议",MB_YESNO|MB_ICONWARNING|MB_DEFBUTTON2)==IDYES;}
 void fullscreen(){full_=!full_;if(full_){oldStyle_=GetWindowLongPtrW(window_,GWL_STYLE);GetWindowPlacement(window_,&placement_);MONITORINFO mi{sizeof(mi)};GetMonitorInfoW(MonitorFromWindow(window_,MONITOR_DEFAULTTONEAREST),&mi);SetWindowLongPtrW(window_,GWL_STYLE,oldStyle_&~WS_OVERLAPPEDWINDOW);SetWindowPos(window_,HWND_TOP,mi.rcMonitor.left,mi.rcMonitor.top,mi.rcMonitor.right-mi.rcMonitor.left,mi.rcMonitor.bottom-mi.rcMonitor.top,SWP_FRAMECHANGED);}else{SetWindowLongPtrW(window_,GWL_STYLE,oldStyle_);SetWindowPlacement(window_,&placement_);SetWindowPos(window_,nullptr,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOZORDER|SWP_FRAMECHANGED);}}
 HWND control(int id){return controls_[id-Server];}
 std::wstring value(int id){wchar_t text[256]{};GetWindowTextW(control(id),text,256);return text;}
 void add(int id,const wchar_t* cls,const wchar_t* label,DWORD style=0){auto h=CreateWindowExW(0,cls,label,WS_CHILD|WS_VISIBLE|WS_TABSTOP|style,0,0,1,1,window_,reinterpret_cast<HMENU>(INT_PTR(id)),nullptr,nullptr);controls_[id-Server]=h;SendMessageW(h,WM_SETFONT,reinterpret_cast<WPARAM>(controlFont_?controlFont_:font_),TRUE);}
 void layout(){if(!control(Server))return;RECT r;GetClientRect(window_,&r);r=logical(r);width_=r.right;height_=r.bottom;int side=r.right-280;bool joined=meeting_.Session().GetState()==MeetingSession::State::Joined;
 auto move=[&](int id,int x,int y,int w,int h){MoveWindow(control(id),pixels(x),pixels(y),pixels(w),pixels(h),TRUE);};
 for(int id:{Server,Room,Identity,Create,Join})ShowWindow(control(id),joined?SW_HIDE:SW_SHOW);
 int formX=52,formY=230,formW=std::min(440,side-96);
 move(Server,formX,formY,formW,36);move(Room,formX,formY+78,formW,36);move(Identity,formX,formY+156,formW,36);move(Create,formX,formY+218,(formW-12)/2,42);move(Join,formX+(formW+12)/2,formY+218,(formW-12)/2,42);
 move(Mode,side-230,24,100,34);move(Fullscreen,side-118,24,94,34);move(Copy,side+20,100,240,36);
 move(Peers,side+20,180,240,std::max(100,int(r.bottom)-530));int yy=r.bottom-334;move(Pin,side+20,yy,116,32);move(Remove,side+144,yy,116,32);
 move(CameraDevice,side+20,r.bottom-243,240,180);move(MicDevice,side+20,r.bottom-175,240,180);move(Refresh,side+20,r.bottom-127,240,32);
 int x=24;for(int id:{Microphone,Camera,Screen,Speaker}){move(id,x,r.bottom-72,126,44);x+=138;}move(Leave,r.right-276,r.bottom-72,118,44);move(End,r.right-146,r.bottom-72,122,44);
 }
 void frame(const std::string& id,VideoFrame f){auto converted=ToBgra(f);if(converted){std::lock_guard lock(frameMutex_);frames_[id]=std::move(converted);}}
 void stopInputs(){screen_.Stop();if(capture_){capture_->StopCamera();capture_->StopMicrophone();}meeting_.SetVideo("off");meeting_.SetMicrophone(false);}
 void shutdown(){if(closed_)return;closed_=true;KillTimer(window_,1);stopInputs();playing_=false;running_=false;if(audioThread_.joinable())audioThread_.join();meeting_.Leave();if(capture_)capture_->Stop();}
 void command(int id){
  const bool joined=meeting_.Session().GetState()==MeetingSession::State::Joined;
  if(id==Fullscreen){fullscreen();return;}
  if(id==Mode){if(!pinned_.empty()){pinned_.clear();focusMode_=speakerMode_=false;}else if(!focusMode_&&!speakerMode_)focusMode_=true;else if(focusMode_){focusMode_=false;speakerMode_=true;}else speakerMode_=false;SetWindowTextW(control(Mode),speakerMode_?L"发言人视图":focusMode_?L"聚焦视图":L"宫格视图");return;}
  if(id==Pin){auto peer=selected();if(!peer.empty())pinned_=pinned_==peer?"":peer;return;}
  if(id==Refresh){if(!capture_->IsCameraCapturing()&&!capture_->IsMicrophoneCapturing())refreshDevices();return;}
  if(id==Copy){if(!joined)return;auto text=L"LumaLive 视频会议\r\n服务器："+value(Server)+L"\r\n会议号："+value(Room);if(OpenClipboard(window_)){auto mem=GlobalAlloc(GMEM_MOVEABLE,(text.size()+1)*sizeof(wchar_t));if(mem){auto ptr=GlobalLock(mem);if(ptr){memcpy(ptr,text.c_str(),(text.size()+1)*sizeof(wchar_t));GlobalUnlock(mem);EmptyClipboard();if(!SetClipboardData(CF_UNICODETEXT,mem))GlobalFree(mem);else status_=L"会议信息已复制，可发送给参会者";}else GlobalFree(mem);}CloseClipboard();}return;}
  if((id==Camera||id==Microphone||id==Screen||id==Leave||id==End||id==Remove)&&!joined)return;
  if((id==Create||id==Join)&&(joined||meeting_.Session().GetState()==MeetingSession::State::Joining))return;
  if(id==Create||id==Join){stopInputs();meeting_.Leave();{std::lock_guard lock(frameMutex_);frames_.clear();levels_.clear();}activeSpeaker_.clear();speakerSelection_.Reset();auto host=utf8(value(Server));auto at=host.rfind(':');int port=9000;if(at!=std::string::npos){try{size_t used=0;auto text=host.substr(at+1);port=std::stoi(text,&used);if(used!=text.size())port=0;}catch(...){port=0;}host.resize(at);}if(port<1||port>65535){status_=L"服务器端口无效，请输入 1–65535";return;}
   self_=utf8(value(Identity));MeetingMedia::Callbacks cb;cb.video=[this](const std::string& peer,VideoFrame f){frame(peer,std::move(f));};cb.audio=[this](const std::string& peer,AudioFrame f){level(peer,f);};
   if(!meeting_.Start(host,static_cast<std::uint16_t>(port),utf8(value(Room)),self_,id==Create,std::move(cb)))status_=wide(meeting_.Session().Status());else status_=L"正在连接会议…";
  }else if(id==Leave){if(!confirmLeave())return;stopInputs();meeting_.Leave();status_=L"已离开会议";}
  else if(id==End){if(meeting_.Session().IsHost()&&MessageBoxW(window_,L"结束后所有成员都会退出会议。确定结束？",L"结束会议",MB_YESNO|MB_ICONWARNING|MB_DEFBUTTON2)==IDYES)meeting_.Session().End();}
  else if(id==Remove){auto peer=selected();if(meeting_.Session().IsHost()&&!peer.empty()&&peer!=self_&&MessageBoxW(window_,(L"将 "+wide(peer)+L" 移出本次会议？").c_str(),L"移出成员",MB_YESNO|MB_ICONQUESTION|MB_DEFBUTTON2)==IDYES)meeting_.Session().Remove(peer);}
  else if(id==Speaker){muted_=!muted_;output_.SetVolume(muted_?0.f:.65f);}
  else if(id==Camera){if(capture_->IsCameraCapturing()){capture_->StopCamera();meeting_.SetVideo("off");}else{screen_.Stop();meeting_.SetVideo("off");auto chosen=SendMessageW(control(CameraDevice),CB_GETCURSEL,0,0);if(chosen<0||size_t(chosen)>=cameras_.size()){status_=L"未找到摄像头，请连接后刷新设备";return;}media::CameraCaptureConfig cfg;cfg.device_id=cameras_[chosen].id;cfg.width=640;cfg.height=480;auto result=capture_->StartCamera(cfg,[this](VideoFrame f){frame(self_,f);meeting_.VideoFrame(f);});if(result.IsOk())meeting_.SetVideo("camera");else status_=wide(result.Message());}}
  else if(id==Screen){if(screen_.IsCapturing()){screen_.Stop();meeting_.SetVideo("off");}else{capture_->StopCamera();meeting_.SetVideo("off");if(screen_.Start([this](VideoFrame f){frame(self_,f);meeting_.VideoFrame(f);}))meeting_.SetVideo("screen");else status_=wide(screen_.LastError());}}
  else if(id==Microphone){if(capture_->IsMicrophoneCapturing()){capture_->StopMicrophone();meeting_.SetMicrophone(false);}else{auto chosen=SendMessageW(control(MicDevice),CB_GETCURSEL,0,0);if(chosen<0||size_t(chosen)>=mics_.size()){status_=L"未找到麦克风，请连接后刷新设备";return;}media::AudioCaptureConfig cfg;cfg.device_id=mics_[chosen].id;cfg.channels=1;auto result=capture_->StartMicrophone(cfg,[this](AudioFrame f){level(self_,f);meeting_.AudioFrame(f);});if(result.IsOk())meeting_.SetMicrophone(true);else status_=wide(result.Message());}}
 }
 void poll(){meeting_.Poll();updateSpeaker();const auto state=meeting_.Session().GetState();const bool joined=state==MeetingSession::State::Joined;playing_=joined;
  if(!joined&&(capture_->IsCameraCapturing()||capture_->IsMicrophoneCapturing()||screen_.IsCapturing()))stopInputs();
  if(joined){const auto& self=meeting_.Session().Members().at(self_);if(self.video=="camera"&&!capture_->IsCameraCapturing()){meeting_.SetVideo("off");status_=L"摄像头已中断，请重新开启";}if(self.video=="screen"&&!screen_.IsCapturing()){meeting_.SetVideo("off");status_=wide(screen_.LastError());}if(self.microphone&&!capture_->IsMicrophoneCapturing()){meeting_.SetMicrophone(false);status_=L"麦克风已中断，请重新开启";}}
  if(state==MeetingSession::State::Failed||state==MeetingSession::State::Ended||state==MeetingSession::State::Removed)status_=wide(meeting_.Session().Status());if(!meeting_.Error().empty())status_=wide(meeting_.Error());if(audioError_.exchange(false))status_=L"扬声器输出不可用";
  for(int id:{Camera,Microphone,Screen,Leave})EnableWindow(control(id),joined);for(int id:{Server,Room,Identity,Create,Join})EnableWindow(control(id),!joined&&state!=MeetingSession::State::Joining);EnableWindow(control(End),meeting_.Session().IsHost());EnableWindow(control(Remove),meeting_.Session().IsHost()&&!selected().empty()&&selected()!=self_);EnableWindow(control(Pin),joined&&!selected().empty());EnableWindow(control(Copy),joined);EnableWindow(control(Mode),joined);EnableWindow(control(CameraDevice),!capture_->IsCameraCapturing());EnableWindow(control(MicDevice),!capture_->IsMicrophoneCapturing());EnableWindow(control(Refresh),!capture_->IsCameraCapturing()&&!capture_->IsMicrophoneCapturing());if(joined!=wasJoined_){wasJoined_=joined;if(joined)connected_=std::chrono::steady_clock::now();layout();}
  SetWindowTextW(control(Camera),capture_->IsCameraCapturing()?L"关闭摄像头":L"开启摄像头");SetWindowTextW(control(Microphone),capture_->IsMicrophoneCapturing()?L"静音":L"开启麦克风");SetWindowTextW(control(Screen),screen_.IsCapturing()?L"停止共享":L"共享屏幕");SetWindowTextW(control(Speaker),muted_?L"恢复扬声器":L"扬声器开启");
  if(joined&&status_==L"正在连接会议…")status_=L"已加入会议 · 摄像头和麦克风由你自主开启";
  std::vector<std::string> roster;for(const auto& [id,member]:meeting_.Session().Members())roster.push_back(id);auto choice=selected();if(roster!=roster_){roster_=roster;SendMessageW(control(Peers),LB_RESETCONTENT,0,0);int index=0,chosen=0;for(const auto& id:roster_){auto label=wide(id);SendMessageW(control(Peers),LB_ADDSTRING,0,reinterpret_cast<LPARAM>(label.c_str()));if(id==choice)chosen=index;++index;}SendMessageW(control(Peers),LB_SETCURSEL,chosen,0);}if(!pinned_.empty()&&!meeting_.Session().Members().count(pinned_))pinned_.clear();SetWindowTextW(control(Pin),!pinned_.empty()&&pinned_==selected()?L"取消固定":L"固定画面");
  {std::lock_guard lock(frameMutex_);for(auto it=frames_.begin();it!=frames_.end();){auto member=meeting_.Session().Members().find(it->first);if(member==meeting_.Session().Members().end()||member->second.video=="off")it=frames_.erase(it);else ++it;}}
  InvalidateRect(control(Peers),nullptr,FALSE);
  InvalidateRect(window_,nullptr,FALSE);
 }
 void text(HDC dc,const std::wstring& s,RECT r,COLORREF color=RGB(232,237,245),HFONT font=nullptr,UINT flags=DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS){auto old=SelectObject(dc,font?font:font_);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,color);DrawTextW(dc,s.c_str(),-1,&r,flags);SelectObject(dc,old);}
 void box(HDC dc,RECT r,COLORREF fill,COLORREF border=RGB(39,45,55),int radius=12){auto b=CreateSolidBrush(fill);auto p=CreatePen(PS_SOLID,1,border);auto ob=SelectObject(dc,b);auto op=SelectObject(dc,p);RoundRect(dc,r.left,r.top,r.right,r.bottom,radius,radius);SelectObject(dc,ob);SelectObject(dc,op);DeleteObject(b);DeleteObject(p);}
 void drawItem(DRAWITEMSTRUCT* d){auto dc=d->hDC;ScaleDC scale(dc,dpi_);auto r=logical(d->rcItem);if(d->CtlID==CameraDevice||d->CtlID==MicDevice){box(dc,r,(d->itemState&ODS_SELECTED)?RGB(24,44,64):RGB(16,19,24));std::wstring label;if(d->itemID!=UINT(-1)){auto n=SendMessageW(d->hwndItem,CB_GETLBTEXTLEN,d->itemID,0);if(n>=0){label.resize(size_t(n)+1);SendMessageW(d->hwndItem,CB_GETLBTEXT,d->itemID,reinterpret_cast<LPARAM>(label.data()));label.resize(size_t(n));}}text(dc,label,{r.left+9,r.top,r.right-6,r.bottom},(d->itemState&ODS_DISABLED)?RGB(86,94,107):RGB(232,237,245));if(d->itemState&ODS_FOCUS){InflateRect(&r,-3,-3);DrawFocusRect(dc,&r);}return;}if(d->CtlID==Peers){if(d->itemID==UINT(-1)||d->itemID>=roster_.size())return;auto id=roster_[d->itemID];auto it=meeting_.Session().Members().find(id);if(it==meeting_.Session().Members().end())return;box(dc,r,(d->itemState&ODS_SELECTED)?RGB(24,44,64):RGB(16,19,24));text(dc,wide(id)+(id==self_?L"（我）":L""),{r.left+12,r.top+5,r.right-12,r.top+29});auto &m=it->second;text(dc,(m.host?L"主持人 · ":L"")+(m.microphone?std::wstring(L"麦克风开"):std::wstring(L"已静音"))+(m.video=="screen"?L" · 共享中":m.video=="camera"?L" · 视频开":L""),{r.left+12,r.top+29,r.right-12,r.bottom-3},RGB(147,159,177));return;}
 bool disabled=d->itemState&ODS_DISABLED;bool primary=d->CtlID==Create||d->CtlID==Join;bool danger=d->CtlID==End;bool active=(d->CtlID==Camera&&capture_&&capture_->IsCameraCapturing())||(d->CtlID==Microphone&&capture_&&capture_->IsMicrophoneCapturing())||(d->CtlID==Screen&&screen_.IsCapturing());COLORREF fill=disabled?RGB(19,22,28):primary?RGB(0,119,216):danger?RGB(77,29,38):active?RGB(18,58,73):RGB(28,33,42);if(d->itemState&ODS_SELECTED)fill=RGB(40,67,92);box(dc,r,fill,disabled?RGB(29,33,40):primary?RGB(0,145,245):RGB(48,58,72));wchar_t label[128]{};GetWindowTextW(d->hwndItem,label,128);text(dc,label,r,disabled?RGB(86,94,107):RGB(232,237,245),nullptr,DT_CENTER|DT_VCENTER|DT_SINGLELINE);if(d->itemState&ODS_FOCUS){InflateRect(&r,-4,-4);DrawFocusRect(dc,&r);}}
 std::wstring connectionHint(const std::string& id){if(id==self_)return L"";auto state=meeting_.PeerState(id);if(state=="connected")return L"";if(state=="failed"||state=="closed")return L"连接失败";if(state=="disconnected")return L"网络中断，等待恢复";return L"正在连接…";}
 void paint(HDC dc){ScaleDC scale(dc,dpi_);RECT r;GetClientRect(window_,&r);r=logical(r);FillRect(dc,&r,background_);int side=r.right-280;const auto &members=meeting_.Session().Members();bool joined=meeting_.Session().GetState()==MeetingSession::State::Joined;
 text(dc,L"LumaLive",{24,18,180,52},RGB(232,237,245),titleFont_);text(dc,L"视频会议",{188,22,330,52},RGB(147,159,177));
 auto line=CreatePen(PS_SOLID,1,RGB(39,45,55));auto old=SelectObject(dc,line);MoveToEx(dc,24,76,nullptr);LineTo(dc,r.right-24,76);MoveToEx(dc,side,96,nullptr);LineTo(dc,side,r.bottom-100);MoveToEx(dc,24,r.bottom-92,nullptr);LineTo(dc,r.right-24,r.bottom-92);SelectObject(dc,old);DeleteObject(line);
 text(dc,L"会议信息",{side+20,80,r.right-20,100},RGB(147,159,177));text(dc,L"参会成员  "+std::to_wstring(members.size()),{side+20,142,r.right-20,175});text(dc,L"摄像头",{side+20,r.bottom-272,r.right-20,r.bottom-246},RGB(147,159,177));text(dc,L"麦克风",{side+20,r.bottom-204,r.right-20,r.bottom-178},RGB(147,159,177));
 if(!joined){text(dc,L"让每一次沟通，都清晰可见。",{52,108,side-24,155},RGB(232,237,245),titleFont_);text(dc,L"创建新会议，或输入会议号加入。设备将在你开启后使用。",{52,158,side-24,192},RGB(147,159,177));text(dc,L"信令服务器",{52,201,side-24,226},RGB(147,159,177));text(dc,L"会议号",{52,279,side-24,304},RGB(147,159,177));text(dc,L"你的显示名称",{52,357,side-24,382},RGB(147,159,177));}
 else{auto seconds=std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now()-connected_).count();auto duration=std::to_wstring(seconds/60)+L":"+(seconds%60<10?L"0":L"")+std::to_wstring(seconds%60);text(dc,L"●  会议中  ·  "+value(Room)+L"  ·  "+duration,{24,90,side-24,122},RGB(112,199,175));std::vector<std::string> shown;std::string focus=pinned_;if(focus.empty()&&speakerMode_){focus=activeSpeaker_;if(focus.empty()&&!members.empty())focus=members.begin()->first;}if(focus.empty()&&focusMode_&&!members.empty()){focus=selected();if(focus.empty())focus=members.begin()->first;}if(!focus.empty()&&members.count(focus))shown.push_back(focus);else for(auto &[id,m]:members)shown.push_back(id);int cols=shown.size()>4?3:shown.size()>1?2:1;int rows=std::max(1,int((shown.size()+cols-1)/cols));int w=(side-48-(cols-1)*12)/cols,h=(r.bottom-278-(rows-1)*12)/rows;int i=0;
 for(const auto &id:shown){const auto &member=members.at(id);RECT t{24+(i%cols)*(w+12),138+(i/cols)*(h+12),24+(i%cols)*(w+12)+w,138+(i/cols)*(h+12)+h};box(dc,t,RGB(16,19,24),id==pinned_?RGB(0,145,245):RGB(39,45,55));std::shared_ptr<VideoFrame> f;{std::lock_guard lock(frameMutex_);auto it=frames_.find(id);if(it!=frames_.end())f=it->second;}auto hint=connectionHint(id);if(f&&member.video!="off"&&hint.empty()){double ratio=std::min(double(w-4)/f->width,double(h-42)/f->height);int fw=int(f->width*ratio),fh=int(f->height*ratio);BITMAPINFO info{};info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=f->width;info.bmiHeader.biHeight=-LONG(f->height);info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;StretchDIBits(dc,t.left+(w-fw)/2,t.top+(h-42-fh)/2,fw,fh,0,0,f->width,f->height,f->data.data(),&info,DIB_RGB_COLORS,SRCCOPY);}else{int cx=(t.left+t.right)/2,cy=(t.top+t.bottom-32)/2;box(dc,{cx-32,cy-40,cx+32,cy+24},RGB(26,45,63),RGB(35,62,84),64);text(dc,wide(id).substr(0,1),{cx-32,cy-40,cx+32,cy+24},RGB(142,198,244),titleFont_,DT_CENTER|DT_VCENTER|DT_SINGLELINE);text(dc,!hint.empty()?hint:member.video=="off"?L"摄像头已关闭":L"正在接收画面…",{t.left+12,cy+34,t.right-12,cy+60},RGB(125,138,157),nullptr,DT_CENTER|DT_VCENTER|DT_SINGLELINE);}text(dc,wide(id)+(id==self_?L"（我）":L"")+(member.host?L" · 主持人":L"")+(member.microphone?L"":L" · 已静音"),{t.left+14,t.bottom-36,t.right-14,t.bottom-8});++i;}}
 text(dc,status_,{24,r.bottom-136,side-24,r.bottom-100},RGB(147,159,177));
 }
 static LRESULT CALLBACK proc(HWND h,UINT m,WPARAM w,LPARAM l){auto self=reinterpret_cast<MeetingWindow*>(GetWindowLongPtrW(h,GWLP_USERDATA));if(m==WM_NCCREATE){self=static_cast<MeetingWindow*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams);self->window_=h;SetWindowLongPtrW(h,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(self));}if(!self)return DefWindowProcW(h,m,w,l);
  switch(m){case WM_CTLCOLOREDIT:case WM_CTLCOLORLISTBOX:{auto dc=reinterpret_cast<HDC>(w);SetTextColor(dc,RGB(228,236,248));SetBkColor(dc,RGB(8,10,13));return reinterpret_cast<LRESULT>(self->background_);}case WM_DRAWITEM:self->drawItem(reinterpret_cast<DRAWITEMSTRUCT*>(l));return TRUE;case WM_DPICHANGED:{self->setDpi(HIWORD(w));auto r=reinterpret_cast<RECT*>(l);SetWindowPos(h,nullptr,r->left,r->top,r->right-r->left,r->bottom-r->top,SWP_NOZORDER|SWP_NOACTIVATE);return 0;}case WM_MEASUREITEM:reinterpret_cast<MEASUREITEMSTRUCT*>(l)->itemHeight=self->pixels(reinterpret_cast<MEASUREITEMSTRUCT*>(l)->CtlID==Peers?58:30);return TRUE;case WM_SIZE:self->layout();return 0;case WM_GETMINMAXINFO:reinterpret_cast<MINMAXINFO*>(l)->ptMinTrackSize={self->pixels(1100),self->pixels(760)};return 0;case WM_TIMER:self->poll();return 0;case WM_COMMAND:if(HIWORD(w)==BN_CLICKED)self->command(LOWORD(w));return 0;case WM_ERASEBKGND:return 1;case WM_PAINT:{PAINTSTRUCT ps;auto dc=BeginPaint(h,&ps);RECT r;GetClientRect(h,&r);auto mem=CreateCompatibleDC(dc);auto bitmap=CreateCompatibleBitmap(dc,r.right,r.bottom);auto previous=SelectObject(mem,bitmap);self->paint(mem);BitBlt(dc,0,0,r.right,r.bottom,mem,0,0,SRCCOPY);SelectObject(mem,previous);DeleteObject(bitmap);DeleteDC(mem);EndPaint(h,&ps);return 0;}case WM_CLOSE:if(!self->confirmLeave())return 0;self->shutdown();DestroyWindow(h);return 0;case WM_DESTROY:PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);
 }
bool checkControls(){
 if(meeting_.Session().GetState()!=MeetingSession::State::Joined||roster_.size()<3)return false;
 const auto chosen=selected();command(Pin);if(pinned_!=chosen)return false;command(Mode);if(!pinned_.empty()||focusMode_||speakerMode_)return false;
 command(Mode);if(!focusMode_)return false;command(Mode);if(!speakerMode_||focusMode_)return false;command(Mode);if(focusMode_||speakerMode_)return false;
 const bool before=muted_;command(Speaker);if(muted_==before)return false;command(Speaker);if(muted_!=before)return false;
 RECT beforeRect{},afterRect{};GetWindowRect(window_,&beforeRect);command(Fullscreen);if(!full_)return false;command(Fullscreen);GetWindowRect(window_,&afterRect);
 if(full_||!EqualRect(&beforeRect,&afterRect))return false;
 poll();return !IsWindowEnabled(control(Create))&&!IsWindowEnabled(control(Join))&&IsWindowEnabled(control(Leave))&&IsWindowEnabled(control(Copy));
}
bool render(const wchar_t* path){RECT r;GetClientRect(window_,&r);auto dc=GetDC(window_);auto mem=CreateCompatibleDC(dc);auto bitmap=CreateCompatibleBitmap(dc,r.right,r.bottom);ReleaseDC(window_,dc);if(!mem||!bitmap){if(bitmap)DeleteObject(bitmap);if(mem)DeleteDC(mem);return false;}auto previous=SelectObject(mem,bitmap);paint(mem);for(auto control:controls_){if(!(GetWindowLongPtrW(control,GWL_STYLE)&WS_VISIBLE))continue;RECT area;GetWindowRect(control,&area);MapWindowPoints(nullptr,window_,reinterpret_cast<POINT*>(&area),2);int saved=SaveDC(mem);SetViewportOrgEx(mem,area.left,area.top,nullptr);SendMessageW(control,WM_PRINT,reinterpret_cast<WPARAM>(mem),PRF_CLIENT|PRF_NONCLIENT);wchar_t cls[32]{};GetClassNameW(control,cls,32);if(lstrcmpiW(cls,L"EDIT")==0)SendMessageW(control,WM_PRINTCLIENT,reinterpret_cast<WPARAM>(mem),PRF_CLIENT);RestoreDC(mem,saved);}SelectObject(mem,previous);BITMAPINFO info{};info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=r.right;info.bmiHeader.biHeight=-r.bottom;info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;std::vector<unsigned char> pixels(size_t(r.right)*r.bottom*4);bool ok=GetDIBits(mem,bitmap,0,r.bottom,pixels.data(),&info,DIB_RGB_COLORS)==r.bottom;DeleteObject(bitmap);DeleteDC(mem);if(!ok)return false;BITMAPFILEHEADER file{};file.bfType=0x4d42;file.bfOffBits=sizeof(file)+sizeof(info.bmiHeader);file.bfSize=file.bfOffBits+DWORD(pixels.size());std::ofstream output(std::filesystem::path(path),std::ios::binary);output.write(reinterpret_cast<const char*>(&file),sizeof(file));output.write(reinterpret_cast<const char*>(&info.bmiHeader),sizeof(info.bmiHeader));output.write(reinterpret_cast<const char*>(pixels.data()),pixels.size());return bool(output);}
public:
 ~MeetingWindow(){shutdown();if(controlFont_)DeleteObject(controlFont_);if(font_)DeleteObject(font_);if(titleFont_)DeleteObject(titleFont_);DeleteObject(background_);}
 int Run(HINSTANCE instance,int show){WNDCLASSW wc{};wc.hInstance=instance;wc.lpfnWndProc=proc;wc.lpszClassName=L"LumaMeetingPreview";wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);RegisterClassW(&wc);window_=CreateWindowExW(0,wc.lpszClassName,L"LumaLive · 视频会议",WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN,CW_USEDEFAULT,CW_USEDEFAULT,1280,850,nullptr,nullptr,instance,this);if(!window_)return 1;font_=CreateFontW(-16,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,0,0,0,0,L"Microsoft YaHei UI");titleFont_=CreateFontW(-24,0,0,0,FW_SEMIBOLD,FALSE,FALSE,FALSE,DEFAULT_CHARSET,0,0,0,0,L"Microsoft YaHei UI");BOOL dark=TRUE;DwmSetWindowAttribute(window_,20,&dark,sizeof(dark));
  add(Server,L"EDIT",L"127.0.0.1:9000",WS_BORDER|ES_AUTOHSCROLL);add(Room,L"EDIT",L"luma-meeting",WS_BORDER|ES_AUTOHSCROLL);add(Identity,L"EDIT",(L"member-"+std::to_wstring(GetCurrentProcessId())).c_str(),WS_BORDER|ES_AUTOHSCROLL);
  for(auto [id,label]:{std::pair<int,const wchar_t*>{Create,L"创建会议"},{Join,L"加入会议"},{Leave,L"离开会议"},{Camera,L"开启摄像头"},{Microphone,L"开启麦克风"},{Screen,L"共享屏幕"},{Speaker,L"扬声器开启"},{Remove,L"移出成员"},{End,L"结束会议"}})add(id,L"BUTTON",label,BS_OWNERDRAW);
  add(Peers,L"LISTBOX",L"参会成员",LBS_OWNERDRAWFIXED|LBS_HASSTRINGS|LBS_NOTIFY|WS_VSCROLL);
  add(CameraDevice,L"COMBOBOX",L"摄像头",CBS_DROPDOWNLIST|CBS_OWNERDRAWFIXED|CBS_HASSTRINGS|WS_VSCROLL);add(MicDevice,L"COMBOBOX",L"麦克风",CBS_DROPDOWNLIST|CBS_OWNERDRAWFIXED|CBS_HASSTRINGS|WS_VSCROLL);
  for(auto [id,label]:{std::pair<int,const wchar_t*>{Refresh,L"刷新设备"},{Pin,L"固定画面"},{Mode,L"宫格视图"},{Fullscreen,L"全屏"},{Copy,L"复制会议信息"}})add(id,L"BUTTON",label,BS_OWNERDRAW);
  setDpi(GetDpiForWindow(window_));SetWindowPos(window_,nullptr,0,0,pixels(1280),pixels(850),SWP_NOMOVE|SWP_NOZORDER);capture_=media::CreateDeviceCaptureService();auto started=capture_->Start();if(!started.IsOk())status_=wide(started.Message());refreshDevices();layout();poll();wchar_t renderPath[32768]{};if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_RENDER_PATH",renderPath,32768)){bool fixtureRequested=false;wchar_t test[512]{};if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_TEST_SERVER",test,512)){fixtureRequested=true;SetWindowTextW(control(Server),test);if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_TEST_ROOM",test,512))SetWindowTextW(control(Room),test);if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_TEST_IDENTITY",test,512))SetWindowTextW(control(Identity),test);bool create=GetEnvironmentVariableW(L"LUMALIVE_MEETING_TEST_ACTION",test,512)&&wcscmp(test,L"create")==0;command(create?Create:Join);auto until=std::chrono::steady_clock::now()+std::chrono::seconds(5);while(std::chrono::steady_clock::now()<until){poll();if(meeting_.Session().Members().size()>=3)break;Sleep(20);}}
  bool controlsPassed=true;wchar_t check[8]{};if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_TEST_CONTROLS",check,8))controlsPassed=checkControls();wchar_t dimension[32]{};if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_RENDER_DPI",dimension,32))setDpi(UINT(std::clamp(_wtoi(dimension),96,192)));int rw=1280,rh=850;if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_RENDER_WIDTH",dimension,32))rw=std::clamp(_wtoi(dimension),1100,3000);if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_RENDER_HEIGHT",dimension,32))rh=std::clamp(_wtoi(dimension),760,2000);SetWindowPos(window_,nullptr,0,0,pixels(rw),pixels(rh),SWP_NOMOVE|SWP_NOZORDER);layout();ShowWindow(window_,SW_SHOWNOACTIVATE);UpdateWindow(window_);bool ready=!fixtureRequested||(meeting_.Session().GetState()==MeetingSession::State::Joined&&meeting_.Session().Members().size()>=3);bool ok=std::filesystem::path(renderPath).is_absolute()&&render(renderPath);shutdown();DestroyWindow(window_);return !controlsPassed?4:!ready?3:ok?0:2;}audioThread_=std::thread([this]{auto next=std::chrono::steady_clock::now();while(running_){if(playing_){if(!output_.Push(meeting_.MixAudio()))audioError_=true;}else output_.Close();next+=std::chrono::milliseconds(10);if(next<std::chrono::steady_clock::now()-std::chrono::milliseconds(30))next=std::chrono::steady_clock::now();std::this_thread::sleep_until(next);}output_.Close();});SetTimer(window_,1,33,nullptr);ShowWindow(window_,show);MSG message{};while(GetMessageW(&message,nullptr,0,0)>0){if(message.message==WM_KEYDOWN&&message.wParam==VK_ESCAPE&&full_){fullscreen();continue;}if(!IsDialogMessageW(window_,&message)){TranslateMessage(&message);DispatchMessageW(&message);}}return int(message.wParam);
 }
};
}
int RunMeetingPreview(HINSTANCE instance,int show){SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);auto com=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);if(FAILED(com))return 1;int result;{MeetingWindow window;result=window.Run(instance,show);}CoUninitialize();return result;}
}
