#include "StudioPreview.hpp"
#include "MeetingMedia.hpp"
#include "MeetingSpeaker.hpp"
#include "AiPanel.hpp"
#include "CaptionOverlay.hpp"
#include "UiTheme.hpp"
#include "PreviewMedia.hpp"
#include "AudioOutput.hpp"
#include "DeviceCaptureFactory.hpp"
#include "ScreenCaptureService.hpp"
#include <commctrl.h>
#include <objbase.h>
#include <fstream>
#include <filesystem>
#include <dwmapi.h>
#include <array>
#include <thread>
#include <windowsx.h>
#include <chrono>
#include <algorithm>
namespace luma::client::ui::preview {
namespace {
std::wstring wide(const std::string& s){int n=MultiByteToWideChar(CP_UTF8,0,s.data(),int(s.size()),nullptr,0);std::wstring out(n,L' ');MultiByteToWideChar(CP_UTF8,0,s.data(),int(s.size()),out.data(),n);return out;}
std::string utf8(const std::wstring& s){int n=WideCharToMultiByte(CP_UTF8,0,s.data(),int(s.size()),nullptr,0,nullptr,nullptr);std::string out(n,' ');WideCharToMultiByte(CP_UTF8,0,s.data(),int(s.size()),out.data(),n,nullptr,nullptr);return out;}
class MeetingWindow : public HostedMeeting {
 enum{Server=200,Room,Identity,Create,Join,Leave,Camera,Microphone,Screen,Speaker,Peers,Remove,End,CameraDevice,MicDevice,Refresh,Pin,Mode,Fullscreen,Copy,ReconnectPeer,Ai,Advanced,Confirm,Cancel,Count};
 HWND window_{};bool embedded_{false};std::array<HWND,Count-Server> controls_{};HFONT font_{};HBRUSH background_=CreateSolidBrush(RGB(8,10,13));
 AiPanel ai_{AiPanel::Context::Meeting};MeetingMedia meeting_;std::unique_ptr<media::IDeviceCaptureService> capture_;media::ScreenCaptureService screen_;AudioOutput output_;
 std::mutex frameMutex_;std::map<std::string,std::shared_ptr<VideoFrame>> frames_;std::string self_;std::wstring status_=UiLabel(L"设备默认关闭，准备好后再开启摄像头和麦克风",L"Camera and microphone are off. Turn them on when you are ready.");
 std::atomic<bool> running_{true},playing_{false},audioError_{false};std::thread audioThread_;bool closed_=false,muted_=false;std::vector<std::string> roster_;
 std::vector<media::CaptureDeviceInfo> cameras_,mics_;
 std::string pinned_,activeSpeaker_;bool focusMode_=false,speakerMode_=false,full_=false;
 std::map<std::string,std::pair<float,std::chrono::steady_clock::time_point>> levels_;
 MeetingSpeaker speakerSelection_;WINDOWPLACEMENT placement_{sizeof(WINDOWPLACEMENT)};LONG_PTR oldStyle_{};
 std::chrono::steady_clock::time_point connected_{};bool wasJoined_=false;HFONT titleFont_{};
 enum class Pending {None,Leave,End,Remove,Close};
 Pending pending_=Pending::None;std::string pendingPeer_;bool advanced_=false,closeApproved_=false;
 UINT dpi_=96;HFONT controlFont_{};
 int width_=1280,height_=850;
 struct FormLayout{int x,width,title,description,room,identity,actions,advanced,server,note;};
 FormLayout formLayout()const{
  const int width=std::min(480,width_-96),x=(width_-width)/2;
  if(height_<740){const int top=std::max(84,std::min(104,height_-536));return {x,width,top,top+44,top+114,top+194,top+252,top+308,top+382,top+(advanced_?434:356)};}
  return {x,width,128,181,258,344,414,478,548,advanced_?609:534};
 }
 int pixels(int value)const{return MulDiv(value,int(dpi_),96);}
 RECT logical(RECT r)const{return {MulDiv(r.left,96,int(dpi_)),MulDiv(r.top,96,int(dpi_)),MulDiv(r.right,96,int(dpi_)),MulDiv(r.bottom,96,int(dpi_))};}
 struct ScaleDC{HDC dc;int saved;ScaleDC(HDC h,UINT dpi):dc(h),saved(SaveDC(h)){SetMapMode(dc,MM_ANISOTROPIC);SetWindowExtEx(dc,96,96,nullptr);SetViewportExtEx(dc,int(dpi),int(dpi),nullptr);}~ScaleDC(){RestoreDC(dc,saved);}};
 void setDpi(UINT dpi){dpi_=std::max(96u,dpi);auto next=UiTheme::Font(pixels(15));if(next){for(auto h:controls_)if(h)SendMessageW(h,WM_SETFONT,reinterpret_cast<WPARAM>(next),TRUE);if(controlFont_)DeleteObject(controlFont_);controlFont_=next;}if(control(Peers))SendMessageW(control(Peers),LB_SETITEMHEIGHT,0,pixels(58));for(int id:{CameraDevice,MicDevice})if(control(id)){SendMessageW(control(id),CB_SETITEMHEIGHT,0,pixels(30));UiTheme::SetComboDpi(control(id),dpi_);}layout();InvalidateRect(window_,nullptr,TRUE);}

 std::string selected(){auto i=SendMessageW(control(Peers),LB_GETCURSEL,0,0);return i>=0&&size_t(i)<roster_.size()?roster_[i]:std::string{};}
 void refreshDevices(){
  auto fill=[&](int id,std::vector<media::CaptureDeviceInfo>& items,media::CaptureDeviceType kind){auto old=SendMessageW(control(id),CB_GETCURSEL,0,0);std::string previous=old>=0&&size_t(old)<items.size()?items[old].id:"";items=capture_->EnumerateDevices(kind).devices;SendMessageW(control(id),CB_RESETCONTENT,0,0);int chosen=0;for(size_t i=0;i<items.size();++i){auto name=wide(items[i].name);SendMessageW(control(id),CB_ADDSTRING,0,reinterpret_cast<LPARAM>(name.c_str()));if(items[i].id==previous)chosen=int(i);}if(items.empty())SendMessageW(control(id),CB_ADDSTRING,0,reinterpret_cast<LPARAM>(UiLabel(L"未找到设备",L"No device found")));SendMessageW(control(id),CB_SETCURSEL,chosen,0);};
  fill(CameraDevice,cameras_,media::CaptureDeviceType::Camera);fill(MicDevice,mics_,media::CaptureDeviceType::Microphone);
 }
 void level(const std::string& id,const AudioFrame& audio){const auto peak=Peak(audio);std::lock_guard lock(frameMutex_);levels_[id]={peak,std::chrono::steady_clock::now()};}
 void updateSpeaker(){
  const auto now=std::chrono::steady_clock::now();std::set<std::string> eligible;std::map<std::string,float> fresh;
  for(const auto& [id,member]:meeting_.Session().Members())if(member.microphone)eligible.insert(id);
  {std::lock_guard lock(frameMutex_);for(auto it=levels_.begin();it!=levels_.end();){
   if(!eligible.count(it->first)||now-it->second.second>=std::chrono::milliseconds(350)){it=levels_.erase(it);continue;}
   fresh[it->first]=it->second.first;++it;
  }}
  activeSpeaker_=speakerSelection_.Update(eligible,fresh,now);
 }
 void requestConfirmation(Pending action,const std::string& peer={}){pending_=action;pendingPeer_=peer;layout();SetFocus(control(Cancel));InvalidateRect(window_,nullptr,FALSE);}
 bool confirmLeave(){if(closeApproved_){closeApproved_=false;return true;}if(!meeting_.Session().IsHost())return true;requestConfirmation(Pending::Close);return false;}
 void resolveConfirmation(bool accept){const auto action=pending_;const auto peer=pendingPeer_;pending_=Pending::None;pendingPeer_.clear();layout();if(!accept){SetFocus(control(Leave));return;}if(action==Pending::Close){closeApproved_=true;PostMessageW(embedded_?GetParent(window_):window_,WM_CLOSE,0,0);return;}if(action==Pending::Leave){stopInputs();meeting_.Leave();status_=UiLabel(L"已离开会议",L"You left the meeting");}else if(action==Pending::End&&meeting_.Session().IsHost())meeting_.Session().End();else if(action==Pending::Remove&&meeting_.Session().IsHost()&&peer!=self_)meeting_.Session().Remove(peer);}
 void fullscreen(){if(embedded_){SendMessageW(GetParent(window_),ToggleWorkspaceFullscreen,0,0);return;}full_=!full_;if(full_){oldStyle_=GetWindowLongPtrW(window_,GWL_STYLE);GetWindowPlacement(window_,&placement_);MONITORINFO mi{sizeof(mi)};GetMonitorInfoW(MonitorFromWindow(window_,MONITOR_DEFAULTTONEAREST),&mi);SetWindowLongPtrW(window_,GWL_STYLE,oldStyle_&~WS_OVERLAPPEDWINDOW);SetWindowPos(window_,HWND_TOP,mi.rcMonitor.left,mi.rcMonitor.top,mi.rcMonitor.right-mi.rcMonitor.left,mi.rcMonitor.bottom-mi.rcMonitor.top,SWP_FRAMECHANGED);}else{SetWindowLongPtrW(window_,GWL_STYLE,oldStyle_);SetWindowPlacement(window_,&placement_);SetWindowPos(window_,nullptr,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOZORDER|SWP_FRAMECHANGED);}}
 HWND control(int id){return controls_[id-Server];}
 std::wstring value(int id){wchar_t text[256]{};GetWindowTextW(control(id),text,256);return text;}
 static LRESULT CALLBACK childProc(HWND h,UINT m,WPARAM w,LPARAM l,UINT_PTR id,DWORD_PTR data){auto self=reinterpret_cast<MeetingWindow*>(data);if(m==WM_GETDLGCODE&&self->pending_!=Pending::None&&l&&reinterpret_cast<MSG*>(l)->message==WM_KEYDOWN&&reinterpret_cast<MSG*>(l)->wParam==VK_ESCAPE)return DefSubclassProc(h,m,w,l)|DLGC_WANTMESSAGE;if(m==WM_KEYDOWN&&w==VK_ESCAPE&&self->pending_!=Pending::None){self->resolveConfirmation(false);return 0;}if(m==WM_NCDESTROY)RemoveWindowSubclass(h,childProc,id);return DefSubclassProc(h,m,w,l);}
 void add(int id,const wchar_t* cls,const wchar_t* label,DWORD style=0){auto h=CreateWindowExW(0,cls,label,WS_CHILD|WS_VISIBLE|WS_TABSTOP|style,0,0,1,1,window_,reinterpret_cast<HMENU>(INT_PTR(id)),nullptr,nullptr);controls_[id-Server]=h;SetWindowSubclass(h,childProc,3,reinterpret_cast<DWORD_PTR>(this));if(lstrcmpW(cls,L"BUTTON")==0)UiTheme::InstallHover(h);if(lstrcmpW(cls,L"COMBOBOX")==0)UiTheme::InstallCombo(h);SendMessageW(h,WM_SETFONT,reinterpret_cast<WPARAM>(controlFont_?controlFont_:font_),TRUE);}
 void layout(){if(!control(Server))return;RECT r;GetClientRect(window_,&r);r=logical(r);width_=r.right;height_=r.bottom;const int side=r.right-280;const bool joined=meeting_.Session().GetState()==MeetingSession::State::Joined;
 auto move=[&](int id,int x,int y,int w,int h){MoveWindow(control(id),pixels(x),pixels(y),pixels(std::max(1,w)),pixels(std::max(1,h)),TRUE);};
 for(int id:{Room,Identity,Create,Join,Advanced})ShowWindow(control(id),joined?SW_HIDE:SW_SHOW);
 ShowWindow(control(Server),!joined&&advanced_?SW_SHOW:SW_HIDE);
 for(int id:{Mode,Copy,Peers,Pin,Remove,CameraDevice,MicDevice,Refresh,ReconnectPeer,Microphone,Camera,Screen,Speaker,Leave,End})ShowWindow(control(id),joined?SW_SHOW:SW_HIDE);
 const auto form=formLayout();const int formW=form.width,formX=form.x;
 move(Room,formX,form.room,formW,40);move(Identity,formX,form.identity,formW,40);
 move(Create,formX,form.actions,(formW-12)/2,44);move(Join,formX+(formW+12)/2,form.actions,(formW-12)/2,44);
 move(Advanced,formX,form.advanced,formW,34);move(Server,formX,form.server,formW,40);
 move(Ai,r.right-386,22,110,36);ShowWindow(control(Ai),!embedded_&&joined?SW_SHOW:SW_HIDE);move(Mode,r.right-264,22,124,36);move(Fullscreen,r.right-132,22,108,36);move(Copy,side+20,100,240,36);
 move(Peers,side+20,166,240,std::max(58,int(r.bottom)-504));int yy=r.bottom-334;move(Pin,side+20,yy,116,34);move(Remove,side+144,yy,116,34);
 move(CameraDevice,side+20,r.bottom-243,240,180);move(MicDevice,side+20,r.bottom-175,240,180);move(Refresh,side+20,r.bottom-127,116,32);move(ReconnectPeer,side+144,r.bottom-127,116,32);
 int x=24;const int gap=8,bw=std::max(84,std::min(136,(int(r.right)-328)/4));for(int id:{Microphone,Camera,Screen,Speaker}){move(id,x,r.bottom-72,bw,44);x+=bw+gap;}move(Leave,r.right-276,r.bottom-72,118,44);move(End,r.right-146,r.bottom-72,122,44);
 const bool confirming=pending_!=Pending::None;for(int id:{Confirm,Cancel})ShowWindow(control(id),confirming?SW_SHOW:SW_HIDE);
 move(Confirm,side-218,r.bottom-196,96,36);move(Cancel,side-112,r.bottom-196,88,36);
 }
 void frame(const std::string& id,VideoFrame f){auto converted=ToBgra(f);if(converted){std::lock_guard lock(frameMutex_);frames_[id]=std::move(converted);}}
 void stopInputs(){screen_.Stop();if(capture_){capture_->StopCamera();capture_->StopMicrophone();}meeting_.SetVideo("off");meeting_.SetMicrophone(false);}
 void shutdown(){if(closed_)return;closed_=true;ai_.Close();KillTimer(window_,1);stopInputs();playing_=false;running_=false;if(audioThread_.joinable())audioThread_.join();meeting_.Leave();if(capture_)capture_->Stop();}
 void command(int id){
  const bool joined=meeting_.Session().GetState()==MeetingSession::State::Joined;
  if(id==Confirm||id==Cancel){resolveConfirmation(id==Confirm);return;}
  if(pending_!=Pending::None)return;
  if(id==Advanced){advanced_=!advanced_;SetWindowTextW(control(Advanced),advanced_?UiLabel(L"收起连接设置",L"Hide connection settings"):UiLabel(L"连接设置",L"Connection settings"));layout();InvalidateRect(window_,nullptr,FALSE);return;}
  if(id==Ai){if(embedded_)SendMessageW(GetParent(window_),OpenMeetingAssistant,0,0);else ai_.Open(window_);return;}
  if(id==Fullscreen){fullscreen();return;}
  if(id==Mode){if(!pinned_.empty()){pinned_.clear();focusMode_=speakerMode_=false;}else if(!focusMode_&&!speakerMode_)focusMode_=true;else if(focusMode_){focusMode_=false;speakerMode_=true;}else speakerMode_=false;SetWindowTextW(control(Mode),speakerMode_?UiLabel(L"发言人视图",L"Speaker view"):focusMode_?UiLabel(L"聚焦视图",L"Focus view"):UiLabel(L"宫格视图",L"Gallery view"));return;}
  if(id==Pin){auto peer=selected();if(!peer.empty())pinned_=pinned_==peer?"":peer;return;}
  if(id==ReconnectPeer){auto peer=selected();status_=meeting_.Reconnect(peer)?UiLabel(L"正在重连所选成员",L"Reconnecting selected participant"):UiLabel(L"当前无法重连，请选择其他成员",L"Cannot reconnect. Select another participant.");return;}
  if(id==Refresh){if(!capture_->IsCameraCapturing()&&!capture_->IsMicrophoneCapturing())refreshDevices();return;}
  if(id==Copy){if(!joined)return;auto text=UiLabel(L"LumaLive 视频会议\r\n服务器：",L"LumaLive meeting\r\nServer: ")+value(Server)+UiLabel(L"\r\n会议号：",L"\r\nMeeting ID: ")+value(Room);if(OpenClipboard(window_)){auto mem=GlobalAlloc(GMEM_MOVEABLE,(text.size()+1)*sizeof(wchar_t));if(mem){auto ptr=GlobalLock(mem);if(ptr){memcpy(ptr,text.c_str(),(text.size()+1)*sizeof(wchar_t));GlobalUnlock(mem);EmptyClipboard();if(!SetClipboardData(CF_UNICODETEXT,mem))GlobalFree(mem);else status_=UiLabel(L"会议信息已复制，可发送给参会者",L"Meeting details copied. Share them with your participants.");}else GlobalFree(mem);}CloseClipboard();}return;}
  if((id==Camera||id==Microphone||id==Screen||id==Leave||id==End||id==Remove)&&!joined)return;
  if((id==Create||id==Join)&&(joined||meeting_.Session().GetState()==MeetingSession::State::Joining))return;
  if(id==Create||id==Join){if(embedded_&&!SendMessageW(GetParent(window_),RequestMeetingMedia,0,0)){status_=UiLabel(L"\u8bf7\u5148\u79bb\u5f00\u901a\u8bdd\u623f\u95f4\uff0c\u518d\u52a0\u5165\u4f1a\u8bae",L"Leave the call room before joining a meeting.");return;}ai_.session.Reset();stopInputs();meeting_.Leave();{std::lock_guard lock(frameMutex_);frames_.clear();levels_.clear();}activeSpeaker_.clear();speakerSelection_.Reset();auto host=utf8(value(Server));auto at=host.rfind(':');int port=9000;if(at!=std::string::npos){try{size_t used=0;auto text=host.substr(at+1);port=std::stoi(text,&used);if(used!=text.size())port=0;}catch(...){port=0;}host.resize(at);}if(port<1||port>65535){status_=UiLabel(L"服务器端口无效，请输入 1–65535",L"Invalid server port. Enter a number from 1 to 65535.");return;}
   self_=utf8(value(Identity));MeetingMedia::Callbacks cb;cb.video=[this](const std::string& peer,VideoFrame f){frame(peer,std::move(f));};cb.audio=[this](const std::string& peer,AudioFrame f){level(peer,f);ai_.session.Submit(peer,f);};
   if(!meeting_.Start(host,static_cast<std::uint16_t>(port),utf8(value(Room)),self_,id==Create,std::move(cb)))status_=UiLabel(L"无法加入会议，请检查会议号、显示名称和连接设置。",L"Cannot join. Check the meeting ID, display name and connection settings.");else status_=UiLabel(L"正在连接会议…",L"Connecting to meeting...");
  }else if(id==Leave){if(meeting_.Session().IsHost()){requestConfirmation(Pending::Leave);return;}stopInputs();meeting_.Leave();status_=UiLabel(L"已离开会议",L"You left the meeting");}
  else if(id==End){if(meeting_.Session().IsHost())requestConfirmation(Pending::End);}
  else if(id==Remove){auto peer=selected();if(meeting_.Session().IsHost()&&!peer.empty()&&peer!=self_)requestConfirmation(Pending::Remove,peer);}
  else if(id==Speaker){muted_=!muted_;output_.SetVolume(muted_?0.f:.65f);}
  else if(id==Camera){if(capture_->IsCameraCapturing()){capture_->StopCamera();meeting_.SetVideo("off");}else{screen_.Stop();meeting_.SetVideo("off");auto chosen=SendMessageW(control(CameraDevice),CB_GETCURSEL,0,0);if(chosen<0||size_t(chosen)>=cameras_.size()){status_=UiLabel(L"未找到摄像头，请连接后刷新设备",L"No camera found. Connect one and refresh devices.");return;}media::CameraCaptureConfig cfg;cfg.device_id=cameras_[chosen].id;cfg.width=640;cfg.height=480;auto result=capture_->StartCamera(cfg,[this](VideoFrame f){frame(self_,f);meeting_.VideoFrame(f);});if(result.IsOk())meeting_.SetVideo("camera");else status_=UiLabel(L"无法开启设备，请检查设备连接和系统权限。",L"Cannot start the device. Check its connection and system permissions.");}}
  else if(id==Screen){if(screen_.IsCapturing()){screen_.Stop();meeting_.SetVideo("off");}else{capture_->StopCamera();meeting_.SetVideo("off");if(screen_.Start([this](VideoFrame f){frame(self_,f);meeting_.VideoFrame(f);}))meeting_.SetVideo("screen");else status_=UiLabel(L"屏幕共享已中断，请重新开启。",L"Screen sharing stopped. Start it again to reconnect.");}}
  else if(id==Microphone){if(capture_->IsMicrophoneCapturing()){capture_->StopMicrophone();meeting_.SetMicrophone(false);}else{auto chosen=SendMessageW(control(MicDevice),CB_GETCURSEL,0,0);if(chosen<0||size_t(chosen)>=mics_.size()){status_=UiLabel(L"未找到麦克风，请连接后刷新设备",L"No microphone found. Connect one and refresh devices.");return;}media::AudioCaptureConfig cfg;cfg.device_id=mics_[chosen].id;cfg.channels=1;auto result=capture_->StartMicrophone(cfg,[this](AudioFrame f){level(self_,f);ai_.session.Submit(self_,f);meeting_.AudioFrame(f);});if(result.IsOk())meeting_.SetMicrophone(true);else status_=UiLabel(L"无法开启设备，请检查设备连接和系统权限。",L"Cannot start the device. Check its connection and system permissions.");}}
 }
 void poll(){meeting_.Poll();updateSpeaker();const auto state=meeting_.Session().GetState();const bool joined=state==MeetingSession::State::Joined;playing_=joined;
  if(!joined&&(capture_->IsCameraCapturing()||capture_->IsMicrophoneCapturing()||screen_.IsCapturing()))stopInputs();
  if(joined){const auto& self=meeting_.Session().Members().at(self_);if(self.video=="camera"&&!capture_->IsCameraCapturing()){meeting_.SetVideo("off");status_=UiLabel(L"摄像头已中断，请重新开启",L"Camera disconnected. Turn it on again to reconnect.");}if(self.video=="screen"&&!screen_.IsCapturing()){meeting_.SetVideo("off");status_=UiLabel(L"屏幕共享已中断，请重新开启。",L"Screen sharing stopped. Start it again to reconnect.");}if(self.microphone&&!capture_->IsMicrophoneCapturing()){meeting_.SetMicrophone(false);status_=UiLabel(L"麦克风已中断，请重新开启",L"Microphone disconnected. Turn it on again to reconnect.");}}
  if(state==MeetingSession::State::Failed)status_=UiLabel(L"连接失败，请检查连接设置后重新加入。",L"Connection failed. Check connection settings and join again.");else if(state==MeetingSession::State::Ended)status_=UiLabel(L"会议已结束",L"The meeting has ended");else if(state==MeetingSession::State::Removed)status_=UiLabel(L"主持人已将你移出会议",L"The host removed you from the meeting");if(!meeting_.Error().empty())status_=UiLabel(L"媒体连接出现问题，请尝试重连。",L"There is a media connection problem. Try reconnecting.");if(audioError_.exchange(false))status_=UiLabel(L"扬声器输出不可用",L"Speaker output is unavailable");
  for(int id:{Camera,Microphone,Screen,Leave})EnableWindow(control(id),joined);for(int id:{Server,Room,Identity,Create,Join})EnableWindow(control(id),!joined&&state!=MeetingSession::State::Joining);EnableWindow(control(End),meeting_.Session().IsHost());EnableWindow(control(Remove),meeting_.Session().IsHost()&&!selected().empty()&&selected()!=self_);EnableWindow(control(Pin),joined&&!selected().empty());EnableWindow(control(Copy),joined);EnableWindow(control(ReconnectPeer),joined&&!selected().empty()&&selected()!=self_&&meeting_.PeerState(selected())!="reconnecting");EnableWindow(control(Mode),joined);EnableWindow(control(CameraDevice),!capture_->IsCameraCapturing());EnableWindow(control(MicDevice),!capture_->IsMicrophoneCapturing());EnableWindow(control(Refresh),!capture_->IsCameraCapturing()&&!capture_->IsMicrophoneCapturing());if(joined!=wasJoined_){if(!joined){ai_.session.Enable(false);pending_=Pending::None;pendingPeer_.clear();}wasJoined_=joined;if(joined)connected_=std::chrono::steady_clock::now();layout();}
  SetWindowTextW(control(Camera),capture_->IsCameraCapturing()?UiLabel(L"关闭摄像头",L"Camera off"):UiLabel(L"开启摄像头",L"Camera on"));SetWindowTextW(control(Microphone),capture_->IsMicrophoneCapturing()?UiLabel(L"静音",L"Mute"):UiLabel(L"开启麦克风",L"Unmute"));SetWindowTextW(control(Screen),screen_.IsCapturing()?UiLabel(L"停止共享",L"Stop sharing"):UiLabel(L"共享屏幕",L"Share screen"));SetWindowTextW(control(Speaker),muted_?UiLabel(L"恢复扬声器",L"Enable speaker"):UiLabel(L"扬声器开启",L"Speaker on"));
  if(joined&&status_==UiLabel(L"正在连接会议…",L"Connecting to meeting..."))status_=UiLabel(L"已加入会议 · 摄像头和麦克风由你自主开启",L"You joined. Turn on your camera and microphone when ready.");
  std::vector<std::string> roster;for(const auto& [id,member]:meeting_.Session().Members())roster.push_back(id);auto choice=selected();if(roster!=roster_){roster_=roster;SendMessageW(control(Peers),LB_RESETCONTENT,0,0);int index=0,chosen=0;for(const auto& id:roster_){auto label=wide(id);SendMessageW(control(Peers),LB_ADDSTRING,0,reinterpret_cast<LPARAM>(label.c_str()));if(id==choice)chosen=index;++index;}SendMessageW(control(Peers),LB_SETCURSEL,chosen,0);}if(!pinned_.empty()&&!meeting_.Session().Members().count(pinned_))pinned_.clear();SetWindowTextW(control(Pin),!pinned_.empty()&&pinned_==selected()?UiLabel(L"取消固定",L"Unpin"):UiLabel(L"固定画面",L"Pin video"));
  {std::lock_guard lock(frameMutex_);for(auto it=frames_.begin();it!=frames_.end();){auto member=meeting_.Session().Members().find(it->first);if(member==meeting_.Session().Members().end()||member->second.video=="off")it=frames_.erase(it);else ++it;}}
  InvalidateRect(control(Peers),nullptr,FALSE);
  InvalidateRect(window_,nullptr,FALSE);
 }
 void text(HDC dc,const std::wstring& s,RECT r,COLORREF color=RGB(232,237,245),HFONT font=nullptr,UINT flags=DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS){auto old=SelectObject(dc,font?font:font_);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,color);DrawTextW(dc,s.c_str(),-1,&r,flags);SelectObject(dc,old);}
 void box(HDC dc,RECT r,COLORREF fill,COLORREF border=RGB(39,45,55),int radius=12){auto b=CreateSolidBrush(fill);auto p=CreatePen(PS_SOLID,1,border);auto ob=SelectObject(dc,b);auto op=SelectObject(dc,p);RoundRect(dc,r.left,r.top,r.right,r.bottom,radius,radius);SelectObject(dc,ob);SelectObject(dc,op);DeleteObject(b);DeleteObject(p);}
 void drawItem(DRAWITEMSTRUCT* d){if(d->CtlID!=Peers&&d->CtlID!=CameraDevice&&d->CtlID!=MicDevice){const bool active=(d->CtlID==Camera&&capture_&&capture_->IsCameraCapturing())||(d->CtlID==Microphone&&capture_&&capture_->IsMicrophoneCapturing())||(d->CtlID==Screen&&screen_.IsCapturing());UiTheme::DrawButton(*d,controlFont_?controlFont_:font_,d->CtlID==Join,active,d->CtlID==End||d->CtlID==Confirm);return;}auto dc=d->hDC;ScaleDC scale(dc,dpi_);auto r=logical(d->rcItem);if(d->CtlID==CameraDevice||d->CtlID==MicDevice){box(dc,r,(d->itemState&ODS_SELECTED)?RGB(24,44,64):RGB(16,19,24));std::wstring label;if(d->itemID!=UINT(-1)){auto n=SendMessageW(d->hwndItem,CB_GETLBTEXTLEN,d->itemID,0);if(n>=0){label.resize(size_t(n)+1);SendMessageW(d->hwndItem,CB_GETLBTEXT,d->itemID,reinterpret_cast<LPARAM>(label.data()));label.resize(size_t(n));}}text(dc,label,{r.left+9,r.top,r.right-6,r.bottom},(d->itemState&ODS_DISABLED)?RGB(86,94,107):RGB(232,237,245));if(d->itemState&ODS_FOCUS){InflateRect(&r,-3,-3);DrawFocusRect(dc,&r);}return;}if(d->CtlID==Peers){if(d->itemID==UINT(-1)||d->itemID>=roster_.size())return;auto id=roster_[d->itemID];auto it=meeting_.Session().Members().find(id);if(it==meeting_.Session().Members().end())return;box(dc,r,(d->itemState&ODS_SELECTED)?RGB(24,44,64):RGB(16,19,24));text(dc,wide(id)+(id==self_?UiLabel(L"（我）",L" (you)"):L""),{r.left+12,r.top+5,r.right-12,r.top+29});auto &m=it->second;text(dc,(m.host?UiLabel(L"主持人 · ",L"Host · "):L"")+(m.microphone?std::wstring(UiLabel(L"麦克风开",L"Mic on")):std::wstring(UiLabel(L"已静音",L"Muted")))+(m.video=="screen"?UiLabel(L" · 共享中",L" · Sharing"):m.video=="camera"?UiLabel(L" · 视频开",L" · Video on"):L""),{r.left+12,r.top+29,r.right-12,r.bottom-3},RGB(147,159,177));if(d->itemState&ODS_FOCUS){InflateRect(&r,-3,-3);DrawFocusRect(dc,&r);}return;}
 }
 std::wstring connectionHint(const std::string& id){if(id==self_)return L"";auto state=meeting_.PeerState(id);if(state=="connected")return L"";if(state=="failed"||state=="closed")return UiLabel(L"连接失败",L"Connection failed");if(state=="reconnecting")return UiLabel(L"正在重新连接…",L"Reconnecting...");if(state=="disconnected")return UiLabel(L"网络中断，等待恢复",L"Connection lost. Waiting to reconnect.");return UiLabel(L"正在连接…",L"Connecting...");}
 void paint(HDC dc){ScaleDC scale(dc,dpi_);RECT r;GetClientRect(window_,&r);r=logical(r);FillRect(dc,&r,background_);int side=r.right-280;const auto &members=meeting_.Session().Members();bool joined=meeting_.Session().GetState()==MeetingSession::State::Joined;
 text(dc,UiLabel(L"视频会议",L"Meetings"),{28,18,310,56},UiTheme::Text,titleFont_);
 auto line=CreatePen(PS_SOLID,1,UiTheme::Border);auto old=SelectObject(dc,line);MoveToEx(dc,24,76,nullptr);LineTo(dc,r.right-24,76);if(joined){MoveToEx(dc,side,96,nullptr);LineTo(dc,side,r.bottom-100);MoveToEx(dc,24,r.bottom-92,nullptr);LineTo(dc,r.right-24,r.bottom-92);}SelectObject(dc,old);DeleteObject(line);
 if(joined){text(dc,UiLabel(L"会议信息",L"Meeting details"),{side+20,80,r.right-20,100},UiTheme::Muted);text(dc,std::wstring(UiLabel(L"参会成员  ",L"Participants  "))+std::to_wstring(members.size()),{side+20,138,r.right-20,162});text(dc,UiLabel(L"摄像头",L"Camera"),{side+20,r.bottom-272,r.right-20,r.bottom-246},UiTheme::Muted);text(dc,UiLabel(L"麦克风",L"Microphone"),{side+20,r.bottom-204,r.right-20,r.bottom-178},UiTheme::Muted);}
 if(!joined){const auto form=formLayout();const int formW=form.width,formX=form.x;
 text(dc,UiLabel(L"下一场交流，从这里开始",L"Your next conversation starts here"),{formX,form.title,formX+formW,form.title+40},UiTheme::Text,titleFont_);
 text(dc,UiLabel(L"创建会议，或使用会议号与团队相聚。",L"Create a meeting or join your team with a meeting ID."),{formX,form.description,formX+formW,form.description+32},UiTheme::Muted);
 text(dc,UiLabel(L"会议号",L"Meeting ID"),{formX,form.room-30,formX+formW,form.room-4},UiTheme::Muted);
 text(dc,UiLabel(L"你的显示名称",L"Your display name"),{formX,form.identity-30,formX+formW,form.identity-4},UiTheme::Muted);
 if(advanced_)text(dc,UiLabel(L"服务器地址",L"Server address"),{formX,form.server-30,formX+formW,form.server-4},UiTheme::Muted);
 text(dc,UiLabel(L"摄像头和麦克风默认关闭，由你决定何时开启。",L"Your camera and microphone stay off until you turn them on."),{formX,form.note,formX+formW,form.note+40},UiTheme::Muted,nullptr,DT_LEFT|DT_WORDBREAK);
 }
 else{auto seconds=std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now()-connected_).count();auto duration=std::to_wstring(seconds/60)+L":"+(seconds%60<10?L"0":L"")+std::to_wstring(seconds%60);text(dc,UiLabel(L"●  会议中  ·  ",L"●  In meeting  ·  ")+value(Room)+L"  ·  "+duration,{24,90,side-24,122},RGB(112,199,175));std::vector<std::string> shown;std::string focus=pinned_;if(focus.empty()&&speakerMode_){focus=activeSpeaker_;if(focus.empty()&&!members.empty())focus=members.begin()->first;}if(focus.empty()&&focusMode_&&!members.empty()){focus=selected();if(focus.empty())focus=members.begin()->first;}if(!focus.empty()&&members.count(focus))shown.push_back(focus);else for(auto &[id,m]:members)shown.push_back(id);int cols=shown.size()>4?3:shown.size()>1?2:1;int rows=std::max(1,int((shown.size()+cols-1)/cols));const int stageBottom=pending_==Pending::None?r.bottom-140:r.bottom-266;int w=(side-48-(cols-1)*12)/cols,h=std::max(48,(stageBottom-138-(rows-1)*12)/rows);int i=0;
 for(const auto &id:shown){const auto &member=members.at(id);RECT t{24+(i%cols)*(w+12),138+(i/cols)*(h+12),24+(i%cols)*(w+12)+w,138+(i/cols)*(h+12)+h};box(dc,t,RGB(16,19,24),id==pinned_?RGB(0,145,245):RGB(39,45,55));std::shared_ptr<VideoFrame> f;{std::lock_guard lock(frameMutex_);auto it=frames_.find(id);if(it!=frames_.end())f=it->second;}auto hint=connectionHint(id);if(f&&member.video!="off"&&hint.empty()){double ratio=std::min(double(w-4)/f->width,double(h-42)/f->height);int fw=int(f->width*ratio),fh=int(f->height*ratio);BITMAPINFO info{};info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=f->width;info.bmiHeader.biHeight=-LONG(f->height);info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;StretchDIBits(dc,t.left+(w-fw)/2,t.top+(h-42-fh)/2,fw,fh,0,0,f->width,f->height,f->data.data(),&info,DIB_RGB_COLORS,SRCCOPY);}else{int cx=(t.left+t.right)/2,cy=(t.top+t.bottom-32)/2;const bool shortTile=h<180;const int radius=shortTile?20:32,avatarTop=shortTile?t.top+8:cy-40;if(h>=120){box(dc,{cx-radius,avatarTop,cx+radius,avatarTop+radius*2},RGB(26,45,63),RGB(35,62,84),64);text(dc,wide(id).substr(0,1),{cx-radius,avatarTop,cx+radius,avatarTop+radius*2},RGB(142,198,244),titleFont_,DT_CENTER|DT_VCENTER|DT_SINGLELINE);}const int hintTop=shortTile?(h>=120?t.top+52:t.top+8):cy+34;text(dc,!hint.empty()?hint:member.video=="off"?UiLabel(L"摄像头已关闭",L"Camera is off"):UiLabel(L"正在接收画面…",L"Waiting for video..."),{t.left+12,hintTop,t.right-12,std::min(hintTop+26,int(t.bottom)-40)},RGB(125,138,157),nullptr,DT_CENTER|DT_VCENTER|DT_SINGLELINE);}if(hint.empty()){const auto caption=ai_.session.CaptionFor(id);DrawCaptionOverlay(dc,{t.left+2,t.top+2,t.right-2,t.bottom-42},wide(caption.original),wide(caption.translated),font_);}text(dc,wide(id)+(id==self_?UiLabel(L"（我）",L" (you)"):L"")+(member.host?UiLabel(L" · 主持人",L" · Host"):L"")+(member.microphone?L"":UiLabel(L" · 已静音",L" · Muted")),{t.left+14,t.bottom-36,t.right-14,t.bottom-8});++i;}}
 if(pending_!=Pending::None){RECT panel{24,r.bottom-254,side-24,r.bottom-146};box(dc,panel,UiTheme::Elevated,UiTheme::Border);std::wstring prompt=pending_==Pending::Remove?std::wstring(UiLabel(L"移出成员：",L"Remove participant: "))+wide(pendingPeer_):UiLabel(L"你是主持人，继续将结束所有成员的会议。",L"You are the host. Continuing will end the meeting for everyone.");text(dc,prompt,{40,r.bottom-245,side-40,r.bottom-204},UiTheme::Text,nullptr,DT_LEFT|DT_WORDBREAK);}
 text(dc,status_,joined?RECT{24,r.bottom-136,side-24,r.bottom-100}:RECT{48,r.bottom-56,r.right-48,r.bottom-16},UiTheme::Muted,nullptr,DT_LEFT|DT_WORDBREAK);
 }
 static LRESULT CALLBACK proc(HWND h,UINT m,WPARAM w,LPARAM l){auto self=reinterpret_cast<MeetingWindow*>(GetWindowLongPtrW(h,GWLP_USERDATA));if(m==WM_NCCREATE){self=static_cast<MeetingWindow*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams);self->window_=h;SetWindowLongPtrW(h,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(self));}if(!self)return DefWindowProcW(h,m,w,l);
  switch(m){case WM_CTLCOLOREDIT:case WM_CTLCOLORLISTBOX:{auto dc=reinterpret_cast<HDC>(w);SetTextColor(dc,RGB(228,236,248));SetBkColor(dc,RGB(8,10,13));return reinterpret_cast<LRESULT>(self->background_);}case WM_DRAWITEM:self->drawItem(reinterpret_cast<DRAWITEMSTRUCT*>(l));return TRUE;case WM_DPICHANGED:{self->setDpi(HIWORD(w));auto r=reinterpret_cast<RECT*>(l);if(!self->embedded_)SetWindowPos(h,nullptr,r->left,r->top,r->right-r->left,r->bottom-r->top,SWP_NOZORDER|SWP_NOACTIVATE);return 0;}case WM_MEASUREITEM:reinterpret_cast<MEASUREITEMSTRUCT*>(l)->itemHeight=self->pixels(reinterpret_cast<MEASUREITEMSTRUCT*>(l)->CtlID==Peers?58:30);return TRUE;case WM_SIZE:self->layout();return 0;case WM_GETMINMAXINFO:reinterpret_cast<MINMAXINFO*>(l)->ptMinTrackSize={self->pixels(1100),self->pixels(760)};return 0;case WM_TIMER:self->poll();return 0;case WM_COMMAND:if(HIWORD(w)==BN_CLICKED)self->command(LOWORD(w));return 0;case WM_PRINTCLIENT:self->paint(reinterpret_cast<HDC>(w));return 0;case WM_ERASEBKGND:return 1;case WM_PAINT:{PAINTSTRUCT ps;auto dc=BeginPaint(h,&ps);RECT r;GetClientRect(h,&r);auto mem=CreateCompatibleDC(dc);auto bitmap=CreateCompatibleBitmap(dc,r.right,r.bottom);auto previous=SelectObject(mem,bitmap);self->paint(mem);BitBlt(dc,0,0,r.right,r.bottom,mem,0,0,SRCCOPY);SelectObject(mem,previous);DeleteObject(bitmap);DeleteDC(mem);EndPaint(h,&ps);return 0;}case WM_CLOSE:if(!self->confirmLeave())return 0;self->shutdown();DestroyWindow(h);return 0;case WM_DESTROY:self->shutdown();self->window_=nullptr;if(!self->embedded_)PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);
 }
bool checkControls(){
 if(meeting_.Session().GetState()!=MeetingSession::State::Joined||roster_.size()<3)return false;
 const auto chosen=selected();command(Pin);if(pinned_!=chosen)return false;command(Mode);if(!pinned_.empty()||focusMode_||speakerMode_)return false;
 command(Mode);if(!focusMode_)return false;command(Mode);if(!speakerMode_||focusMode_)return false;command(Mode);if(focusMode_||speakerMode_)return false;
 const bool before=muted_;command(Speaker);if(muted_==before)return false;command(Speaker);if(muted_!=before)return false;
 RECT beforeRect{},afterRect{};GetWindowRect(window_,&beforeRect);command(Fullscreen);if(!full_)return false;command(Fullscreen);GetWindowRect(window_,&afterRect);
 if(full_||!EqualRect(&beforeRect,&afterRect))return false;
 poll();return !IsWindowEnabled(control(Create))&&!IsWindowEnabled(control(Join))&&IsWindowEnabled(control(Leave))&&IsWindowEnabled(control(Copy));
}
bool render(const wchar_t* path){RECT r;GetClientRect(window_,&r);auto dc=GetDC(window_);auto mem=CreateCompatibleDC(dc);auto bitmap=CreateCompatibleBitmap(dc,r.right,r.bottom);ReleaseDC(window_,dc);if(!mem||!bitmap){if(bitmap)DeleteObject(bitmap);if(mem)DeleteDC(mem);return false;}auto previous=SelectObject(mem,bitmap);paint(mem);for(auto control:controls_){if(!(GetWindowLongPtrW(control,GWL_STYLE)&WS_VISIBLE))continue;RECT area;GetWindowRect(control,&area);MapWindowPoints(nullptr,window_,reinterpret_cast<POINT*>(&area),2);int saved=SaveDC(mem);SetViewportOrgEx(mem,area.left,area.top,nullptr);SendMessageW(control,WM_PRINT,reinterpret_cast<WPARAM>(mem),PRF_CLIENT|PRF_NONCLIENT);wchar_t cls[32]{};GetClassNameW(control,cls,32);if(lstrcmpiW(cls,L"EDIT")==0)SendMessageW(control,WM_PRINTCLIENT,reinterpret_cast<WPARAM>(mem),PRF_CLIENT);RestoreDC(mem,saved);}SelectObject(mem,previous);BITMAPINFO info{};info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=r.right;info.bmiHeader.biHeight=-r.bottom;info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;std::vector<unsigned char> pixels(size_t(r.right)*r.bottom*4);bool ok=GetDIBits(mem,bitmap,0,r.bottom,pixels.data(),&info,DIB_RGB_COLORS)==r.bottom;DeleteObject(bitmap);DeleteDC(mem);if(!ok)return false;BITMAPFILEHEADER file{};file.bfType=0x4d42;file.bfOffBits=sizeof(file)+sizeof(info.bmiHeader);file.bfSize=file.bfOffBits+DWORD(pixels.size());std::ofstream output(std::filesystem::path(path),std::ios::binary);output.write(reinterpret_cast<const char*>(&file),sizeof(file));output.write(reinterpret_cast<const char*>(&info.bmiHeader),sizeof(info.bmiHeader));output.write(reinterpret_cast<const char*>(pixels.data()),pixels.size());return bool(output);}
public:
 ~MeetingWindow(){shutdown();if(window_&&IsWindow(window_))DestroyWindow(window_);if(controlFont_)DeleteObject(controlFont_);if(font_)DeleteObject(font_);if(titleFont_)DeleteObject(titleFont_);DeleteObject(background_);}
 HWND Handle() const override{return window_;}
 void SetDpi(UINT dpi) override{if(dpi!=dpi_)setDpi(dpi);}
 bool Active() override{auto state=meeting_.Session().GetState();return state==MeetingSession::State::Joining||state==MeetingSession::State::Joined;}
 bool CanClose() override{return confirmLeave();}
 bool CancelPendingAction() override{if(pending_==Pending::None)return false;resolveConfirmation(false);return true;}
 AiPanel& Assistant() override{return ai_;}
 int Run(HINSTANCE instance,int show,HWND parent=nullptr){embedded_=parent!=nullptr;WNDCLASSW wc{};wc.hInstance=instance;wc.lpfnWndProc=proc;wc.lpszClassName=L"LumaMeetingPreview";wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);RegisterClassW(&wc);window_=CreateWindowExW(embedded_?WS_EX_CONTROLPARENT:0,wc.lpszClassName,UiLabel(L"LumaLive · 视频会议",L"LumaLive · Meetings"),(embedded_?(WS_CHILD|WS_CLIPSIBLINGS):(WS_OVERLAPPEDWINDOW))|WS_CLIPCHILDREN,embedded_?0:CW_USEDEFAULT,embedded_?0:CW_USEDEFAULT,1280,850,parent,nullptr,instance,this);if(!window_)return 1;font_=UiTheme::Font(15);titleFont_=UiTheme::Font(24,FW_SEMIBOLD);BOOL dark=TRUE;DwmSetWindowAttribute(window_,20,&dark,sizeof(dark));
  add(Advanced,L"BUTTON",UiLabel(L"连接设置",L"Connection settings"),BS_OWNERDRAW);add(Confirm,L"BUTTON",UiLabel(L"确认",L"Confirm"),BS_OWNERDRAW);add(Cancel,L"BUTTON",UiLabel(L"取消",L"Cancel"),BS_OWNERDRAW);
  add(Ai,L"BUTTON",UiLabel(L"AI 字幕",L"AI captions"),BS_OWNERDRAW);
  add(ReconnectPeer,L"BUTTON",UiLabel(L"重连成员",L"Reconnect"),BS_OWNERDRAW);
  add(Server,L"EDIT",L"127.0.0.1:9000",WS_BORDER|ES_AUTOHSCROLL);add(Room,L"EDIT",L"luma-meeting",WS_BORDER|ES_AUTOHSCROLL);add(Identity,L"EDIT",(L"member-"+std::to_wstring(GetCurrentProcessId())).c_str(),WS_BORDER|ES_AUTOHSCROLL);
  for(auto [id,label]:{std::pair<int,const wchar_t*>{Create,UiLabel(L"创建会议",L"Create meeting")},{Join,UiLabel(L"加入会议",L"Join meeting")},{Leave,UiLabel(L"离开会议",L"Leave")},{Camera,UiLabel(L"开启摄像头",L"Camera on")},{Microphone,UiLabel(L"开启麦克风",L"Unmute")},{Screen,UiLabel(L"共享屏幕",L"Share screen")},{Speaker,UiLabel(L"扬声器开启",L"Speaker on")},{Remove,UiLabel(L"移出成员",L"Remove")},{End,UiLabel(L"结束会议",L"End meeting")}})add(id,L"BUTTON",label,BS_OWNERDRAW);
  add(Peers,L"LISTBOX",UiLabel(L"参会成员",L"Participants"),LBS_OWNERDRAWFIXED|LBS_HASSTRINGS|LBS_NOTIFY|WS_VSCROLL);
  add(CameraDevice,L"COMBOBOX",UiLabel(L"摄像头",L"Camera"),CBS_DROPDOWNLIST|CBS_OWNERDRAWFIXED|CBS_HASSTRINGS|WS_VSCROLL);add(MicDevice,L"COMBOBOX",UiLabel(L"麦克风",L"Microphone"),CBS_DROPDOWNLIST|CBS_OWNERDRAWFIXED|CBS_HASSTRINGS|WS_VSCROLL);
  for(auto [id,label]:{std::pair<int,const wchar_t*>{Refresh,UiLabel(L"刷新设备",L"Refresh")},{Pin,UiLabel(L"固定画面",L"Pin video")},{Mode,UiLabel(L"宫格视图",L"Gallery view")},{Fullscreen,UiLabel(L"全屏",L"Full screen")},{Copy,UiLabel(L"复制会议信息",L"Copy meeting details")}})add(id,L"BUTTON",label,BS_OWNERDRAW);
  for(auto [id,label]:{std::pair<int,const wchar_t*>{Server,UiLabel(L"信令服务器",L"Signaling server")},{Room,UiLabel(L"会议号",L"Meeting ID")},{Identity,UiLabel(L"显示名称",L"Display name")},{Peers,UiLabel(L"参会成员",L"Participants")},{CameraDevice,UiLabel(L"摄像头",L"Camera")},{MicDevice,UiLabel(L"麦克风",L"Microphone")}})SetAccessibleName(control(id),label);
  setDpi(GetDpiForWindow(window_));SetWindowPos(window_,nullptr,0,0,pixels(1280),pixels(850),SWP_NOMOVE|SWP_NOZORDER);capture_=media::CreateDeviceCaptureService();auto started=capture_->Start();if(!started.IsOk())status_=UiLabel(L"设备服务无法启动，请检查系统权限。",L"Device service could not start. Check system permissions.");refreshDevices();layout();poll();wchar_t renderPath[32768]{};if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_RENDER_PATH",renderPath,32768)){bool fixtureRequested=false;wchar_t test[512]{};if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_TEST_SERVER",test,512)){fixtureRequested=true;SetWindowTextW(control(Server),test);if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_TEST_ROOM",test,512))SetWindowTextW(control(Room),test);if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_TEST_IDENTITY",test,512))SetWindowTextW(control(Identity),test);bool create=GetEnvironmentVariableW(L"LUMALIVE_MEETING_TEST_ACTION",test,512)&&wcscmp(test,L"create")==0;command(create?Create:Join);auto until=std::chrono::steady_clock::now()+std::chrono::seconds(5);while(std::chrono::steady_clock::now()<until){poll();if(meeting_.Session().Members().size()>=3)break;Sleep(20);}}
  bool controlsPassed=true;wchar_t check[8]{};if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_TEST_CONTROLS",check,8))controlsPassed=checkControls();wchar_t dimension[32]{};if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_RENDER_DPI",dimension,32))setDpi(UINT(std::clamp(_wtoi(dimension),96,192)));int rw=1280,rh=850;if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_RENDER_WIDTH",dimension,32))rw=std::clamp(_wtoi(dimension),1100,3000);if(GetEnvironmentVariableW(L"LUMALIVE_MEETING_RENDER_HEIGHT",dimension,32))rh=std::clamp(_wtoi(dimension),760,2000);SetWindowPos(window_,nullptr,0,0,pixels(rw),pixels(rh),SWP_NOMOVE|SWP_NOZORDER);layout();ShowWindow(window_,SW_SHOWNOACTIVATE);UpdateWindow(window_);bool ready=!fixtureRequested||(meeting_.Session().GetState()==MeetingSession::State::Joined&&meeting_.Session().Members().size()>=3);bool ok=std::filesystem::path(renderPath).is_absolute()&&render(renderPath);shutdown();DestroyWindow(window_);return !controlsPassed?4:!ready?3:ok?0:2;}audioThread_=std::thread([this]{auto next=std::chrono::steady_clock::now();while(running_){if(playing_){if(!output_.Push(meeting_.MixAudio()))audioError_=true;}else output_.Close();next+=std::chrono::milliseconds(10);if(next<std::chrono::steady_clock::now()-std::chrono::milliseconds(30))next=std::chrono::steady_clock::now();std::this_thread::sleep_until(next);}output_.Close();});SetTimer(window_,1,33,nullptr);ShowWindow(window_,show);if(embedded_)return 0;MSG message{};while(GetMessageW(&message,nullptr,0,0)>0){if(message.message==WM_KEYDOWN&&message.wParam==VK_ESCAPE){if(message.lParam&(LPARAM(1)<<30))continue;if(CancelPendingAction())continue;if(full_){fullscreen();continue;}}if(!IsDialogMessageW(window_,&message)){TranslateMessage(&message);DispatchMessageW(&message);}}return int(message.wParam);
 }
};
}
std::unique_ptr<HostedMeeting> CreateHostedMeeting(HINSTANCE instance,HWND parent){
 auto meeting=std::make_unique<MeetingWindow>();
 if(meeting->Run(instance,SW_HIDE,parent)!=0||!meeting->Handle())return {};
 return meeting;
}
int RunMeetingPreview(HINSTANCE instance,int show){SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);auto com=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);if(FAILED(com))return 1;int result;{MeetingWindow window;result=window.Run(instance,show);}CoUninitialize();return result;}
}
