add_library(luma_signaling STATIC src/SignalingService.cpp src/TcpSignalingServer.cpp src/MeetingService.cpp)
target_include_directories(luma_signaling PUBLIC include)
target_link_libraries(luma_signaling PUBLIC luma_shared)
if(WIN32)
  target_link_libraries(luma_signaling PRIVATE ws2_32)
endif()
target_compile_features(luma_signaling PUBLIC cxx_std_20)
